### ISSUE TITLE
cmd/go: imports fail to resolve in module mode when file contains a leading BOM

### ISSUE THREAD

**Issue by andyTsing** [golang/go#35726]
### What version of Go are you using (`go version`)?
<pre>
$ go version
go version go1.13.4 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\andyTsing\AppData\Local\go-build
set GOENV=C:\Users\andyTsing\AppData\Roaming\go\env  
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\andyTsing\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=D:\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\Temp\TXSSPrinter\BEService\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\ANDYTS~1\AppData\Local\Temp\go-build458686182=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
D:\Temp\TXSSPrinter\BEService>go run .
D:\Temp\TXSSPrinter\BEService>go build

https://github.com/andyTsing/BEService
This is a single-module, multi-package project that worked fine in the early 1.12 release and has had problems since the upgrade to 1.3.
Also, packages that also belong to different subdirectories, some of which have normal imports and some of which have abnormal imports, when I comment out the API section, are
The normal

### What did you expect to see?
A successful retrieval of a dependency.

### What did you see instead?
D:\Temp\TXSSPrinter\BEService>go run .
build github.com/andyTsing/BEService: cannot find module for path github.com/andyTsing/BEService/api

D:\Temp\TXSSPrinter\BEService>go build
build github.com/andyTsing/BEService: cannot find module for path github.com/andyTsing/BEService/api

**Comment by toothrot** [comment]
/cc @bcmills @jayconrod It looks like it is related to a leading BOM character in `router/Router.go`.

Reproduced using https://github.com/andyTsing/BEService/commit/07f4a7fdc545629d7e25a2fc88cffad67ad8ee0e

```
$ xxd router/Router.go 
00000000: efbb bf70 6163 6b61 6765 2072 6f75 7465  ...package route
``` 

This is corrected by gofmt:

```
$ xxd router/Router.go 
00000000: 7061 636b 6167 6520 726f 7574 6572 0a0a  package router..
```

**Comment by toothrot** [comment]
@andyTsing Thanks for the report! Does `go fmt ./router/Router.go` resolve this issue on Windows?

**Comment by andyTsing** [comment]
@toothrot Thank u,following your advice,when i do: go fmt ./router/Router.go,the problem was solved

**Comment by dmitshur** [comment]
Glad to hear that @andyTsing!

If you don't mind, let's re-open this issue to track improving `cmd/go` to report a better error message when this kind of a situation happens.

**Comment by andyTsing** [comment]
@dmitshur OK,It's opened again,I have submitted the correct version. As it is the first time to use github, I am not sure whether @07f4a7f is still intact.
To reproduce the error scenario, manually add the BOM prefix to the router/ router. Go file as described by @toothrot

**Comment by bcmills** [comment]
This is probably a bug in the parser or loader somewhere. Note that the [Go spec](https://golang.org/ref/spec#Source_code_representation) explicitly allows a leading BOM:
> For compatibility with other tools, a compiler may ignore a UTF-8-encoded byte order mark (U+FEFF) if it is the first Unicode code point in the source text. A byte order mark may be disallowed anywhere else in the source.

**Comment by bcmills** [comment]
Curiously, this only manifests as an error in module mode:

```
_gopath/src/github.com/andyTsing/BEService$ git checkout 07f4a7f
[…]

_gopath/src/github.com/andyTsing/BEService$ GO111MODULE=off go build .

_gopath/src/github.com/andyTsing/BEService$ GO111MODULE=on go build .
router/Router.go:13:2: cannot find package
```

**Comment by andyTsing** [comment]
Under normal circumstances, it is unlikely to encounter such errors...
Later, I recalled that the error was probably caused by opening the.go file using Windows' noe.exe,Windows' note.exe processes utf8 format, attaching BOM,The process of the second round made me pay attention to this point. Otherwise, this mistake would be hard to find. Fortunately, @toothrot has rich experience and found the reason.

**Comment by dmitshur** [comment]
@andyTsing Why close this issue? We'd like to improve the go command to report a better error message in this rare situation. Having this issue open is how we can track that work. Do you mind re-opening it?

**Comment by andyTsing** [comment]
Ok, I don't mind. I thought there had been no response recently, so I shut it down. Sorry

**Comment by ValleZ** [comment]
How's progress? This issue means on Windows go fail in most of the cases when people use any common text editor.

**Comment by LiuYinCarl** [comment]
> How's progress? This issue means on Windows go fail in most of the cases when people use any common text editor.

I found a solution good for me. that's #46290

you can try to cedit the golang source file `go/src/cmd/go/internal/imports/scan.go` and then compile the golang.
the code you need to edit is below
```go
func scanFiles(files []string, tags map[string]bool, explicitFiles bool) ([]string, []string, error) {
	imports := make(map[string]bool)
	testImports := make(map[string]bool)
	numFiles := 0
Files:
	for _, name := range files {
		r, err := os.Open(name)
		if err != nil {
			return nil, nil, err
		}
               
               // I add these code to check if the source code is with BOM, if yes, drop the BOM
		var fheader = make([]byte, 3)
		_, err = r.Read(fheader)
		if err != nil {
			fmt.Println("error: ", err)
		}
		if fheader[0] == 0xef && fheader[1] == 0xbb && fheader[2] == 0xbf {
			r.Seek(3, 0)
		} else {
			r.Seek(0, 0)
		}
                ////////// edit end

		var list []string
                // if a file is with BOM, the return list is empty
		data, err := ReadImports(r, false, &list)
		r.Close()
		if err != nil {
			return nil, nil, fmt.Errorf("reading %s: %v", name, err)
		}
// ... ...
}
```
Hope this method is useful for you.
