### ISSUE TITLE
cmd/yacc: Empty grammar fails to compile on Go 1.5

### ISSUE THREAD

**Issue by leocassarani** [golang/go#12154]
I'm testing go1.5rc1 on linux/amd64, and I've come across an issue that prevents the compilation of an empty yacc grammar.

## Steps to reproduce

Create a file named `main.y` with the following contents:

```go
%{
package main

type yyLex struct{}
func (x *yyLex) Lex(yylval *yySymType) int { return 0 }
func (x *yyLex) Error(str string) {}

func main() {}
%}

%union {
}

%%

top: /* empty grammar */

%%
```

Run the following commands:

```
$ go tool yacc -o main.go main.y
$ go build main.go
```

## Expected results

The code should compile without errors.

## Actual results

Compilation fails with the error message: 

```
yaccpar:161[main.go:253]: yyDollar declared and not used
```

## Additional information

The compilation error occurs in the `Parse(yylex yyLexer) int` method on the `*yyParserImpl` type. Line 253 of the generated `main.go` file defines a variable `var yyDollar []yySymType`, which is never referenced by the rest of the auto-generated method.

I've followed the same steps on Go 1.4, and checked that they produce the expected result. In fact, I believe the issue originated with commit 2e78447bafc2dfdfa8b75e01ca3e681741706bbc, which first introduced the `yyDollar` variable.

**Comment by robpike** [comment]
Although I understand this broke a test case, is the test case realistic in any meaningful sense?
