### ISSUE TITLE
cmd/go: vague error when VCS tool not available

### ISSUE THREAD

**Issue by myitcv** [golang/go#26982]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

```
go version go1.11rc1 linux/amd64
```

### Does this issue reproduce with the latest release?

n/a: working with 1.11rc1

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/myitcv/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/tmp/tmp.JrnIrHb6a5"
GOPROXY=""
GORACE=""
GOROOT="/home/myitcv/gos"
GOTMPDIR=""
GOTOOLDIR="/home/myitcv/gos/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/tmp/tmp.yCavsj0ED5/hello/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build243376190=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?

Requires that `bzr` _not_ be in your `PATH`:

```
export GOPATH=$(mktemp -d)
cd $(mktemp -d)
mkdir hello
cd hello
go mod init example.com/hello
cat <<EOD > main.go
package main

import _ "launchpad.net/gocheck"

func main() {}
EOD
go mod tidy
```

### What did you expect to see?

An error message telling me that `bzr` was not available in my `PATH`

### What did you see instead?

Zero exit code and no messages. `go.mod` also untouched:

```
$ cat go.mod
module example.com/hello
```

`go build` at least fails with a non-zero exit code, but a rather vague error message:

```
$ go build
build example.com/hello: cannot find module for path launchpad.net/gocheck
```

In fact in this situation we can be very specific: the error comes about because `bzr` is not in our `PATH`.

**/cc** @rsc @bcmills 

Not sure whether you would consider this a release-blocker? I've not marked it as such for now

**Comment by rsc** [comment]
Filed #27063 for the silent mod tidy and repurposed this for the missing VCS error.
