### ISSUE TITLE
modernc.org/libc@v1.25.0/libc.go:1467:16: undefined: a_load_8 undefined: a_load_16 affected/package: go1.21.3.darwin-arm64

### ISSUE THREAD

**Issue by sichen1234** [golang/go#63711]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.21.3 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
</pre></details>

OS X 14.0
XCode 15.0

### What did you do?

$ go build

### What did you expect to see?

A success message :)

### What did you see instead?

$ go build
# modernc.org/libc
/Users/sichen/go/pkg/mod/modernc.org/libc@v1.25.0/libc.go:1447:14: undefined: a_load_8
/Users/sichen/go/pkg/mod/modernc.org/libc@v1.25.0/libc.go:1451:15: undefined: a_load_16
/Users/sichen/go/pkg/mod/modernc.org/libc@v1.25.0/libc.go:1455:14: undefined: a_load_8
/Users/sichen/go/pkg/mod/modernc.org/libc@v1.25.0/libc.go:1459:16: undefined: a_load_16
/Users/sichen/go/pkg/mod/modernc.org/libc@v1.25.0/libc.go:1463:14: undefined: a_load_8
/Users/sichen/go/pkg/mod/modernc.org/libc@v1.25.0/libc.go:1467:16: undefined: a_load_16

**Comment by dr2chase** [comment]
What are you building, specifically?

I tried to reproduce your bug in the latest version of modernc (1.27.0) with tip, and didn't see it.

Also worked okay with 1.21.3.

Also worked with v1.25.0.

This is on amd64, however.

In addition, modernc uses a lot of unsafe stuff (`git grep unsafe | grep -v test | wc -l` prints 50593 -- that same exercise applied to Go and its runtime only prints 15435) so I'd worry about that, too.

I went looking for a symbol named `a_load_8` in older Go sources and didn't see it (and that would be an unexported symbol anyway).

I think we need more information.

**Comment by rittneje** [comment]
`a_load_8`, etc. are defined in a file named [libc_amd64.go](https://gitlab.com/cznic/libc/-/blob/v1.25.0/libc_amd64.go). Hence it is not possible to compile the code on any other architecture.

Given that the Go compiler is working as intended, you should file an issue against modernc instead. https://gitlab.com/cznic/libc/-/issues

**Comment by sichen1234** [comment]
This is working after I updated to modernc.org/libc@v1.28.0
