### ISSUE TITLE
x/mobile/example: all examples are broken on darwin

### ISSUE THREAD

**Issue by rakyll** [golang/go#11424]
All examples are broken due to https://github.com/golang/mobile/commit/42f0d178764859fe14b76b884b2a8e949ed4429e on darwin. I am opening the issue as a reminder to fix the build.
```
go build golang.org/x/mobile/example/basic
# golang.org/x/mobile/app
../../app/app.go:23: undefined: main
../../app/darwin_amd64.go:58: undefined: mainCalled
../../app/darwin_amd64.go:64: undefined: geom.PixelsPerPt
../../app/darwin_amd64.go:66: undefined: geom.PixelsPerPt
../../app/darwin_amd64.go:68: undefined: configAlt in configAlt.Width
../../app/darwin_amd64.go:68: undefined: geom.PixelsPerPt
../../app/darwin_amd64.go:68: cannot assign to configAlt.Width
../../app/darwin_amd64.go:69: undefined: configAlt in configAlt.Height
../../app/darwin_amd64.go:69: undefined: geom.PixelsPerPt
../../app/darwin_amd64.go:69: cannot assign to configAlt.Height
../../app/darwin_amd64.go:69: too many errors
```

**Comment by nigeltao** [comment]
In the code review at https://go-review.googlesource.com/#/c/11351/ we (crawshaw and I) agreed that I will break Darwin and crawshaw will fix Darwin.

**Comment by crawshaw** [comment]
Yes, I'm working on this. There have been a few google-internal distractions today, but I've almost got darwin/amd64 working. I'll send that out, then do darwin/arm{,64}.

**Comment by rakyll** [comment]
Let's make sure they are all working properly at Gophercon. This was an unfortunate time for significant changes.

**Comment by crawshaw** [comment]
This was fixed several days ago in http://golang.org/cl/11620.

The reason we changed this now was to get the event api we want at the Go 1.5 release in as soon as possible. I'm happy we managed that. It is too bad we didn't find time to rewrite the examples to use it, but anyone trying this before Go 1.5 is stable are working with an experimental package.

**Comment by rakyll** [comment]
Thanks for the update. I have just figured out that my dashboard was red due to an irrelevant problem, the new asset package is broken on darwin/arm.
```
$ gomobile build -target=ios golang.org/x/mobile/example/audio
main.go:42:2: found packages asset (asset.go) and app (asset_darwin_armx.go) in /Users/jbd/src/golang.org/x/mobile/asset
```
It is related to your latest change, would you like to take a look at it? Otherwise, I will send mail out a CL.
