### ISSUE TITLE
help!There are some errors when i run a demo.

### ISSUE THREAD

**Issue by jzyzxx** [golang/go#42657]
### What version of Go are you using (`go version`)?

<pre>
$ 1.9.7

</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GOARCH=amd64
set GOBIN=C:\Go\bin
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\gopath
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\DELL\AppData\Local\Temp\go-build397049711=/tmp/go-build -gno-record-gcc-switches
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config 
</pre></details>

### What did you do?
go install in a demo,there ara logs:

```
# fyne.io/fyne/vendor/golang.org/x/image/vector
..\..\vendor\golang.org\x\image\vector\acc_amd64.s:142: unrecognized instruction "PABSD"
..\..\vendor\golang.org\x\image\vector\acc_amd64.s:144: unrecognized instruction "PMINUD"
..\..\vendor\golang.org\x\image\vector\acc_amd64.s:215: unrecognized instruction "PABSD"
..\..\vendor\golang.org\x\image\vector\acc_amd64.s:217: unrecognized instruction "PMINUD"
..\..\vendor\golang.org\x\image\vector\acc_amd64.s:330: unrecognized instruction "PABSD"
..\..\vendor\golang.org\x\image\vector\acc_amd64.s:332: unrecognized instruction "PMINUD"
..\..\vendor\golang.org\x\image\vector\acc_amd64.s:366: unrecognized instruction "PABSD"
..\..\vendor\golang.org\x\image\vector\acc_amd64.s:368: unrecognized instruction "PMINUD"
..\..\vendor\golang.org\x\image\vector\acc_amd64.s:460: unrecognized instruction "PABSD"
..\..\vendor\golang.org\x\image\vector\acc_amd64.s:462: unrecognized instruction "PMINUD"
..\..\vendor\golang.org\x\image\vector\acc_amd64.s:494: unrecognized instruction "PABSD"
asm: too many errors
# fyne.io/fyne/driver/desktop
..\..\driver\desktop\shortcut.go:21:9: undefined: strings.Builder
# fyne.io/fyne/storage
..\..\storage\uri.go:29:10: undefined: strings.ReplaceAll
..\..\storage\uri.go:30:10: undefined: strings.ReplaceAll
# fyne.io/fyne/vendor/github.com/go-gl/gl/v3.2-core/gl
In file included from D:/MinGW/mingw64/x86_64-w64-mingw32/include/minwindef.h:163,
                 from D:/MinGW/mingw64/x86_64-w64-mingw32/include/windef.h:8,
                 from D:/MinGW/mingw64/x86_64-w64-mingw32/include/windows.h:69,
                 from ..\..\vendor\github.com\go-gl\gl\v3.2-core\gl\package.go:27:
D:/MinGW/mingw64/x86_64-w64-mingw32/include/winnt.h:1554:11: fatal error: x86intrin.h: No such file or directory
 # include <x86intrin.h>
           ^~~~~~~~~~~~~
compilation terminated.
# fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.3/glfw
In file included from D:/MinGW/mingw64/x86_64-w64-mingw32/include/minwindef.h:163,
                 from D:/MinGW/mingw64/x86_64-w64-mingw32/include/windef.h:8,
                 from D:/MinGW/mingw64/x86_64-w64-mingw32/include/windows.h:69,
                 from ./glfw/src/win32_platform.h:68,
                 from ./glfw/src/internal.h:186,
                 from ./glfw/src/context.c:30,
                 from ..\..\vendor\github.com\go-gl\glfw\v3.3\glfw\c_glfw.go:4:
D:/MinGW/mingw64/x86_64-w64-mingw32/include/winnt.h:1554:11: fatal error: x86intrin.h: No such file or directory
 # include <x86intrin.h>
           ^~~~~~~~~~~~~
compilation terminated.
# fyne.io/fyne/layout
..\..\layout\gridlayout.go:63:13: undefined: math.Round
```

### What did you expect to see?
install successfully

### What did you see instead?
some errors above

**Comment by ALTree** [comment]
Please update to a recent version (Go1.15 is the latest) and try again. Go1.9 is no longer supported.

**Comment by mdlayher** [comment]
I don't think this will ever work on Go 1.9.x. At least three of the compilation errors are due to APIs that were added in Go 1.10+, so I don't think there's anything to be done here. I'm going to close this out.

**Comment by jzyzxx** [comment]
> Please update to a recent version (Go1.15 is the latest) and try again. Go1.9 is no longer supported.

thank you,problem is solved.
