### ISSUE TITLE
x/tools/go/packages: Fails to build with 1.11

### ISSUE THREAD

**Issue by codyoss** [golang/go#41383]
### What version of Go are you using (`go version`)?

`go version go1.11.13 linux/amd64`

### Does this issue reproduce with the latest release?
No

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build833573345=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
Tried to build a module that relied on the latest x/tools [commit](https://github.com/golang/tools/commit/8f9ed77dd8e51636de1225a7e25cf48778b97060) with go 1.11.

### What did you expect to see?

It built successfully. 

### What did you see instead?

Fails to build with 1.11.
```
# golang.org/x/tools/go/packages
/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914190812-8f9ed77dd8e5/go/packages/golist_overlay.go:535:7: undefined: strings.ReplaceAll
```

The mod file [declares 1.11](https://github.com/golang/tools/blob/master/go.mod#L3) but uses strings.ReplaceAll which was added in 1.12.

**Comment by davecheney** [comment]
The mod file should be updated to go 1.14, the oldest supported release.

**Comment by mvdan** [comment]
Any particular reason you're using Go 1.11? It's not even receiving security updates at this point.

**Comment by stamblerre** [comment]
I think it just hasn't been updated since then. `gopls` CI currently does test with Go 1.12 and 1.13 since many people cannot update to the latest versions, so the `go.mod` should probably be updated to 1.12.

**Comment by codyoss** [comment]
As of right now we support 1.11+. We like to maintain compatibility for older versions of Go as our cloud client libraries are used by many developers running in many different environments.

I don't expect that go1.11 stays maintained, just would like the mod file to be 1.12+ so the tooling can behave appropriately. I am assuming that `go mod tidy` will then find the correct version of the indirect dependency that we have on this lib when the mod file if updated.

**Comment by heschik** [comment]
@codyoss AFAIK the Go version is not considered when selecting versions. `go get -u` will still break the build.
