### ISSUE TITLE
OSX build broken due to dba9eb3

### ISSUE THREAD

**Issue by marcopeereboom** [golang/go#9674]
$ GOROOT_BOOTSTRAP=$GOROOT ./all.bash
    ##### Building Go bootstrap tool.
    cmd/dist
    # runtime
    runtime/heapdump.go:492: undefined: goexperiment
    runtime/proc1.go:3167: undefined: goexperiment

Didn't look at the code but reverting it makes go compile again.

**Comment by bradfitz** [comment]
Set $GOROOT_BOOTSTRAP to a built Go 1.4 tree, not the dev tree.

Note that the build isn't broken at https://build.golang.org/

**Comment by BlackGriffen** [comment]
So the dev tree is not a standalone build anymore? I now have to have two Golang installs to use it? That seems excessive.

**Comment by minux** [comment]
Please see https://golang.org/s/go15bootstrap

(Generally, if you want to use the master branch, it's recommended to follow
the golang-dev mailing list.)

**Comment by marcopeereboom** [comment]
Alright I follow the 1.4 logic.  The reason this wasn't obvious to me is that in my use of go tip *only* OSX failed.  The other arches I used are not affected by this.  I assume this will remedy itself in the relatively new future.  Thanks for pointing out that document.
