### ISSUE TITLE
cmd/compile: `go build -msan flag` fails with CONVNOP error

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#14589]
On current tip, after the merge of the SSA branch, `go build -msan flag` fails.  (Other directories also fail in similar ways).

    > CC=clang ~/go2/bin/go build -msan flag
    # flag
    ../../../src/flag/flag.go:291: internal compiler error: CONVNOP unrecognized non-integer map[string]*Flag -> *uint8

CC @randall77

**Comment by ianlancetaylor** [comment]
I see there is a special case for flag_race in cmd/compile/internal/gc/ssa.go for `instrumenting`.  That may need to test `instrumenting` rather than `flag_race`.

**Comment by ianlancetaylor** [comment]
https://go-review.googlesource.com/20113

**Comment by randall77** [comment]
When I try to reproduce, I get:

```
$ go build -msan flag
# runtime/msan
runtime/msan/msan.go:17:2: warning: implicit declaration of function '__msan_check_mem_is_initialized' is invalid in C99 [-Wimplicit-function-declaration]
# runtime/msan
/tmp/go-build379857825/runtime/msan/_obj/msan.cgo2.o: In function `__msan_read_go':
runtime/msan/msan.go:17: undefined reference to `__msan_check_mem_is_initialized'
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```
What am I doing wrong?  Do I need to build some other way than make.bash?

**Comment by ianlancetaylor** [comment]
Which version of clang do you have installed?  On GNU/Linux you need at least clang 3.6.

**Comment by randall77** [comment]
That's probably it.  I have:
Ubuntu clang version 3.4-1ubuntu3 (tags/RELEASE_34/final) (based on LLVM 3.4)

Standard Google Ubuntu workstation.  apt-get says clang is already at the newest version.  Ugh.

**Comment by ianlancetaylor** [comment]
Pro tip: `sudo apt-get install clang-3.6`.

**Comment by randall77** [comment]
Well that's very unhelpful of apt-get.
Thanks.
