### ISSUE TITLE
cmd/cover: cannot run in directory with no .go files

### ISSUE THREAD

**Issue by rhysh** [golang/go#33855]
### What version of Go are you using (`go version`)?

<pre>
$ go1.12 version
go version go1.12.9 darwin/amd64
$ go1.13 version
go version go1.13rc1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

This problem is present on `go1.13rc1`. It is not present in `go1.12.9`.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go1.13 env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/rhys/Library/Caches/go-build"
GOENV="/Users/rhys/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/rhys/go"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/Users/rhys/go/version/go1.13"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/Users/rhys/go/version/go1.13/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/tmp/mymod/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/49/zmds5zsn75z1283vtzxyfr5hj7yjq4/T/go-build267819565=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

```
$ mkdir /tmp/mymod
$ cd /tmp/mymod
$ go mod init mymod
$ go tool cover -func=/dev/null
```

### What did you expect to see?

```
$ go1.12 tool cover -func=/dev/null
total:	(statements)	0.0%
```

### What did you see instead?

```
$ go1.13 tool cover -func=/dev/null
cover: cannot run go list: exit status 1
build .: cannot find module for path .

```

`git bisect` points to 4a2d3d06873559df2b6933f260dc8f75c54c9771 (authored in December, but committed in July) as the first "bad" commit.

**Comment by bcmills** [comment]
> Do the integration tests for this code live in src/cmd/go/testdata/script?

I'm not sure, but the new test seems fine there to me.

**Comment by rhysh** [comment]
@gopherbot, please backport to Go 1.13: this is a regression from Go 1.12.
