### ISSUE TITLE
dyld: Symbol not found: _utimensat

### ISSUE THREAD

**Issue by hopehook** [golang/go#50855]
### What version of Go are you using (`go version`)?

if i installed `go1.17.6.darwin-amd64.pkg`
<pre>
$ go version
go version go1.17.6 darwin/amd64
</pre>

if i installed `go1.18beta1.darwin-amd64.pkg`
<pre>
$ go version
dyld: Symbol not found: _utimensat
  Referenced from: /usr/local/go/bin/go
  Expected in: flat namespace

[1]    95321 abort      go version
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

if i installed `go1.17.6.darwin-amd64.pkg`
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/myname/Library/Caches/go-build"
GOENV="/Users/myname/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/myname/lab/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/myname/lab/go:/Users/myname/work/code:/Users/myname/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17.6"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/xc/x_k35ynn063c15716c0d_5pm0000gn/T/go-build335607442=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

if i installed `go1.18beta1.darwin-amd64.pkg`
<pre>
$ go env   
dyld: Symbol not found: _utimensat
  Referenced from: /usr/local/go/bin/go
  Expected in: flat namespace

[1]    95562 abort      go env
</pre>

### What did you do?

I download unstable version `go1.18beta1.darwin-amd64.pkg` from `https://go.dev/dl/`, and installed it to my mac.
When i run `go version` command, it show me that failed message.

### What did you expect to see?

go version go1.18 darwin/amd64

### What did you see instead?

dyld: Symbol not found: _utimensat

**Comment by cherrymui** [comment]
What version of macOS do you use? Thanks.

**Comment by hopehook** [comment]
> What version of macOS do you use? Thanks.

macOS 10.12.5

**Comment by cherrymui** [comment]
Go 1.17 requires macOS 10.13 or later, see https://go.dev/doc/go1.17#darwin

**Comment by mikowiec** [comment]
It was OK with go1.17.7 and macOS SIerra 10.12.6.

After upgrade go to 1.18.beta2 the same issue observed.

Please fix it, due impossible to buy a new mac for golang.

Thank in advance.

**Comment by ianlancetaylor** [comment]
@mikowiec I'm sorry, we have to be able to move forward somehow.  macOS 10.12 is no longer supported by Apple, and we no longer support it either.
