### ISSUE TITLE
cmd/go: test no longer accepts list of files to test

### ISSUE THREAD

**Issue by allenpetersen** [golang/go#26990]
### What version of Go are you using (`go version`)?
go1.11rc1

### Does this issue reproduce with the latest release?
This works in go1.10.3 and go1.11beta3

We might have been doing this wrong for years but we had some Makefiles that listed out the files we wanted to test in a package. With go1.11rc1 in module mode this no longer works.

It looks like this was done as a way to exclude some tests. I've changed our Makefiles so this isn't a blocking issue.

```
root@f677d648e597:/go/src/test# ls
nothing_test.go
root@f677d648e597:/go/src/test# cat nothing_test.go
package nothing

import "testing"

func TestNothing(t *testing.T) {
}
root@f677d648e597:/go/src/test# export GO111MODULE=auto
root@f677d648e597:/go/src/test# go test -count=1
PASS
ok  	test	0.002s
root@f677d648e597:/go/src/test# go test -count=1 ./nothing_test.go
ok  	command-line-arguments	0.002s
root@f677d648e597:/go/src/test# export GO111MODULE=on
root@f677d648e597:/go/src/test# go mod init nothing
go: creating new go.mod: module nothing
root@f677d648e597:/go/src/test# go test -count=1
PASS
ok  	nothing	0.002s
root@f677d648e597:/go/src/test# go test -count=1 ./nothing_test.go
build test: cannot find module for path test
```

I'm fine if this was undefined behavior that will not be supported with modules. Just calling out the change in behavior.

**Comment by andybons** [comment]
@rsc @bcmills @ianlancetaylor

**Comment by rsc** [comment]
Duplicate of #26046, fix pending.
