### ISSUE TITLE
cmd/compile: comparable does not match each comparable type

### ISSUE THREAD

**Issue by blaubaer** [golang/go#51392]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.18-a064a4f29a Sat Feb 26 01:16:03 2022 +0000 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
With the latest revision on `master` ([`a064a4f29a97a4fc7398d1ac9d7c53c5ba0bc646`](https://github.com/golang/go/commit/a064a4f29a97a4fc7398d1ac9d7c53c5ba0bc646)).

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\protected\AppData\Local\go-build
set GOENV=C:\Users\protected\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\protected\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\protected\go
set GOPRIVATE=
set GOWORK=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -fmessage-length=0 -fdebug-prefix-map=C:\Users\protected\AppData\Local\Temp\go-build4145725796=/tmp/go-build -gno-record-gcc-switches
</pre></details>

#### `language.Tag` as Map key

```go
package main

import (
	"fmt"

	"golang.org/x/text/language"
)

func main() {
	aMap := map[language.Tag]string{
		language.German: "foo",
	}
	fmt.Println(aMap)
}
```

#### `language.Tag` as comparable generic parameter

```go
package main

import (
	"fmt"
	"golang.org/x/text/language"
)

func doSomething[K comparable](with map[K]string) {
	fmt.Println("comparable", with)
}

func main() {
	aMap := map[language.Tag]string{
		language.German: "foo",
	}
	doSomething(aMap)
}
```

### What did you expect to see?

1. `language.Tag` as Map key: Is accepted by the compiler.
2. `language.Tag` as comparable generic parameter: Is accepted by the compiler.

### What did you see instead?

1. `language.Tag` as Map key: Is accepted by the compiler.
2. `language.Tag` as comparable generic parameter: Compiler refuses compiling with
    ```
    foo_broken.go:16:13: "golang.org/x/text/language".Tag does not implement comparable
    ```

> ℹ️ I'm pretty sure that this was working at least ~1 week ago with the `master`. With revision [`a289e9ce7514a34cd930469322395bf0e89b59ea`](https://github.com/golang/go/commit/a289e9ce7514a34cd930469322395bf0e89b59ea)) it was working.

**Comment by thanm** [comment]
Biesction points to [163da6feb525a98dab5c1f01d81b2c705ead51ea](https://github.com/golang/go/commit/163da6feb525a98dab5c1f01d81b2c705ead51ea
) as the bad commit, introduced in [CL 387055](https://go-review.googlesource.com/c/go/+/387055).

@griesemer @findleyr

**Comment by findleyr** [comment]
The reason for this is that Tag contains fullTag, which is an interface. This is discussed in more detail in https://github.com/golang/go/issues/51257#issuecomment-1046103263

This is a confusing UX, particularly when the interface is buried deep inside the type. Here the interface is only one level deep, but one can imagine how confusing it could be if the interface were inside several layers of nested structs.

IMO this warrants reconsideration.

**Comment by blaubaer** [comment]
Please correct me if I'm wrong. The specs defines the same rules for map keys as for stuff that implements `comparable`, or? If so either the map implementation in Go is broken in general or how [`163da6feb525a98dab5c1f01d81b2c705ead51ea`](https://github.com/golang/go/commit/163da6feb525a98dab5c1f01d81b2c705ead51ea) change it was too restrictive. I would highly recommend to align both behaviors.

**Comment by findleyr** [comment]
> Please correct me if I'm wrong. The specs defines the same rules for map keys as for stuff that implements comparable

To clarify: no, map keys treat all interfaces as comparable, whereas the `comparable` builtin treats only interfaces that are _statically known_ to be comparable as comparable.

**Comment by ianlancetaylor** [comment]
Closing as dup of #50646 and #51257 and #51138.

**Comment by changkun** [comment]
P.S. I guess Ian was meant to say #51338 other than #51138.

**Comment by ianlancetaylor** [comment]
Thanks, I edited my note.
