### ISSUE TITLE
simd: portable vector types fail to compile in go1.27rc1 with "undefined: simd"

### ISSUE THREAD

**Issue by llxisdsh** [golang/go#80148]
### Go version

go version go1.27rc1 windows/amd64

### Output of `go env` in your module/workspace:

```shell
set AR=ar
set CC=gcc
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_ENABLED=1
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set CXX=g++
set GCCGO=gccgo
set GO111MODULE=on
set GOAMD64=v1
set GOARCH=amd64
set GOAUTH=netrc
set GOBIN=C:\Users\8\go\bin
set GOCACHE=C:\Users\8\AppData\Local\go-build
set GOCACHEPROG=
set GODEBUG=
set GOENV=C:\Users\8\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFIPS140=off
set GOFLAGS=
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=C:\Users\8\AppData\Local\Temp\go-build1360496246=/tmp/go-build -gno-record-gcc-switches
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMOD=E:\code\cc\go.mod
set GOMODCACHE=C:\Users\8\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPACKAGESDRIVER=
set GOPATH=C:\Users\8\go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTELEMETRY=local
set GOTELEMETRYDIR=C:\Users\8\AppData\Roaming\go\telemetry
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.27rc1
set GOWORK=
set PKG_CONFIG=pkg-config
```

### What did you do?

With `GOEXPERIMENT=simd`, I tried to compile a minimal package that uses a portable SIMD vector type.

GOEXPERIMENT=simd
GOOS=windows
GOARCH=amd64
GOVERSION=go1.27rc1

go.mod:

```go
module caseB

go 1.27
```

x.go:

```go
package caseB

import s "simd"

func F() s.Uint8s { return s.BroadcastUint8s(1) }
```

Command:
```sh
GOEXPERIMENT=simd go test -run '^$'
```

Two controls compile successfully in the same environment:
```go
package caseA

import s "simd"

var _ = s.VectorBitSize()
```
and:
```go
package caseD

import a "simd/archsimd"

func F() a.Uint8x16 { return a.BroadcastUint8x16(1) }
```

### What did you see happen?

```text
FAIL    caseB [build failed]
# caseB
.\x.go:3:8: undefined: simd
```

### What did you expect to see?

The portable SIMD vector type should compile when `GOEXPERIMENT=simd` is enabled.

In particular, this should be valid:

```go
import s "simd"

func F() s.Uint8s { return s.BroadcastUint8s(1) }
```

simd.VectorBitSize() and simd/archsimd.Uint8x16 both compile in the same environment, so package availability and GOEXPERIMENT=simd appear to be active. The failure seems specific to portable vector types such as simd.Uint8s.

**Comment by cagedmantis** [comment]
@dr2chase @JunyangShao
