### ISSUE TITLE
x:net error compiling

### ISSUE THREAD

**Issue by lhirlimann** [golang/go#45968]
### What version of Go are you using (`go version`)?

<pre>
[opc@webii ~]$ go version
go version go1.14.12 linux/amd64

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
[opc@webii ~]$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/opc/.cache/go-build"
GOENV="/home/opc/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/tmp/tmp.t1bKwi98lk"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/golang"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build567281578=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
[opc@webii ~]$ go get gitlab.com/yawning/obfs4.git/obfs4proxy
\# golang.org/x/net/http2
/tmp/tmp.t1bKwi98lk/src/golang.org/x/net/http2/transport.go:598:14: undefined: tls.Dialer
[opc@webii ~]

**Comment by mvdan** [comment]
Go 1.14.x is no longer supported. You need Go 1.15 or later. See https://golang.org/pkg/crypto/tls/#Dialer.

If you're stuck on an older Go version, pin older versions of libraries via modules.

**Comment by mvdan** [comment]
Also, see https://golang.org/wiki/Questions.

**Comment by ALTree** [comment]
As mvdan said, you may need to upgrade your Go version. But anyway its looks like Ian decided to keep 1.14 and below able to compile `x/net`, see #45946. Closing here.

**Comment by ianlancetaylor** [comment]
Since this came up five times in 24 hours, I went ahead and patches golang.org/x/net so that it will work with versions of Go before 1.15.  That should fix this problem.  I still strongly encourage everyone to upgrade to a supported version of Go, and I do not promise that this will not break again in the future.
