### ISSUE TITLE
x/tools/cmd/vet: undefined: parser.ParseExprFrom

### ISSUE THREAD

**Issue by attilaolah** [golang/go#11195]
When trying to `go get -u golang.org/x/tools/cmd/vet`, I get the following error:

```
# golang.org/x/tools/go/types
go/types/eval.go:68: undefined: parser.ParseExprFrom
```

Apparently introduced by https://github.com/golang/tools/commit/d241a1448bb9a6aeab0697421853a3ab1fbf243c.

**Comment by ianlancetaylor** [comment]
I think this was just fixed.

**Comment by griesemer** [comment]
This would have required tip of the std repo.

That said, rolling back the change right now since we cannot rely on 1.5 features in x/tools quite yet.

Mea culpa.

**Comment by attilaolah** [comment]
Yep, fixed now, many thanks.

It does work with 1.5 (master) indeed, but then it drove our CI crazy :smile:
