### ISSUE TITLE
sys/unix: incorrect EpollEvent struct, missing functions for ppc64le/ppc64

### ISSUE THREAD

**Issue by laboger** [golang/go#15393]
Please answer these questions before submitting your issue. Thanks!
1. What version of Go are you using (`go version`)?
   go version devel +3e9264c Tue Apr 19 09:21:57 2016 +0000 linux/ppc64le
2. What operating system and processor architecture are you using (`go env`)?
   go version
   go env
   GOARCH="ppc64le"
   GOBIN=""
   GOEXE=""
   GOHOSTARCH="ppc64le"
   GOHOSTOS="linux"
   GOOS="linux"
   GOPATH="/home/boger/golang/sys"
   GORACE=""
   GOROOT="/home/boger/golang/base/go"
   GOTOOLDIR="/home/boger/golang/base/go/pkg/tool/linux_ppc64le"
   CC="gcc"
   GOGCCFLAGS="-fPIC -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build593602443=/tmp/go-build -gno-record-gcc-switches"
   CXX="g++"
   CGO_ENABLED="1"
3. What did you do?
   If possible, provide a recipe for reproducing the error.
   A complete runnable program is good.
   A link on play.golang.org is best.
   Trying to keep with some recent changes to fsnotify.  Originally there was a problem in src/syscall related to the epoll syscalls.  Changes have been made to fsnotify to now use corresponding code in golang.org/x/sys/unix, which is similar but not quite in sync with the main golang repository.  So there are failures with the latest fsnotify code.  Earlier versions (the ones used with distro Docker builds) continue to work fine.
4. What did you expect to see?
   fsnotify test pass on latest
5. What did you see instead?
   fsnotify test failed to build on latest repo (older version v1.2.0 works)

We need to add the changes for the EpollEvent struct that were recently added to the golang repository src/syscall so that golang.org/x/sys/unix also uses the correct structure when the epoll syscalls return information.  In addition, there are some other functions in the golang repository src/syscall that are missing from golang.org/x/sys/unix that need to be added.  Working on a fix.

Here are the errors we are seeing due to missing functions:
go get -u golang.org/x/sys/unix github.com/fsnotify/fsnotify

src/github.com/fsnotify/fsnotify/inotify.go:39: undefined: unix.InotifyInit
src/github.com/fsnotify/fsnotify/inotify_poller.go:48: undefined: unix.Pipe2

**Comment by clnperez** [comment]
I created CL https://go-review.googlesource.com/#/c/22605/ for this issue.

**Comment by tklauser** [comment]
This was fixed by [CL 22605](https://go-review.googlesource.com/#/c/22605/) (commit golang/sys@b776ec3) but the _Fixes_ tag in the commit message is missing _golang/go_ before the issue number, so this issue wasn't closed automatically.

**Comment by bradfitz** [comment]
@tklauser, thanks.
