### ISSUE TITLE
x/sys/unix: some SYS constants disappeared on Darwin

### ISSUE THREAD

**Issue by bradfitz** [golang/go#41868]
We updated our golang.org/x/sys dependency from `v0.0.0-20200812155832` to `v0.0.0-20201008064518-c1f3e3309c71` and got a build breakage on `GOOS=darwin`:

```
../../wireguard-go/tun/tun_darwin.go:141:3: undefined: unix.SYS_IOCTL
../../wireguard-go/tun/tun_darwin.go:162:3: undefined: unix.SYS_CONNECT
../../wireguard-go/tun/tun_darwin.go:241:4: undefined: unix.SYS_GETSOCKOPT
../../wireguard-go/tun/tun_darwin.go:346:3: undefined: unix.SYS_IOCTL
../../wireguard-go/tun/tun_darwin.go:380:3: undefined: unix.SYS_IOCTL
```

/cc @ianlancetaylor @tklauser

**Comment by bcmills** [comment]
`git bisect` reports [CL 250437](https://golang.org/cl/250437) (approved by @bradfitz)

**Comment by ianlancetaylor** [comment]
These were dropped because (as you know) macOS doesn't want us to make direct system calls anyhow.  They want us to go through libSystem in all cases.

**Comment by tklauser** [comment]
The build breakage in `wireguard-go` should be addressed by WireGuard/wireguard-go#42

**Comment by bradfitz** [comment]
@tklauser, thanks for that!

What do you think about reverting the zsysnum file deletions from CL 250437? I don't think Go's migration away from raw system calls should force other people's schedules on when they migrate away from direct system calls.

**Comment by tklauser** [comment]
> @tklauser, thanks for that!
> 
> What do you think about reverting the zsysnum file deletions from CL 250437? I don't think Go's migration away from raw system calls should force other people's schedules on when they migrate away from direct system calls.

@bradfitz yeah, good point. Let's not force other people to migrate away just yet. I'll send a CL to re-add the zsysnum files.
