### ISSUE TITLE
x/unix: Unable to compile for linux/arm: unix/zsyscall_linux_arm.go:2181:14: undefined: Syscall9

### ISSUE THREAD

**Issue by fd0** [golang/go#27475]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

`go version go1.11 linux/amd64`

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/fd0/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/fd0/shared/work/go"
GOPROXY=""
GORACE=""
GOROOT="/home/fd0/sdk/go1.11"
GOTMPDIR=""
GOTOOLDIR="/home/fd0/sdk/go1.11/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build906891150=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?

Build `golang.org/x/sys/unix` for `GOOS=linux` and `GOARCH=arm` (in the context of [restic](https://github.com/restic/restic))

### What did you expect to see?

Package compiles without error.

### What did you see instead?

```
$ GOARCH=arm go build ./unix
# golang.org/x/sys/unix
unix/zsyscall_linux_arm.go:2181:14: undefined: Syscall9
[1]    32452 exit 2     GOARCH=arm go build ./unix
```

I did a `git bisect` from https://github.com/golang/sys/commit/bd9dbc187b6e1dacfdd2722a87e83093c2d7bd6e to https://github.com/golang/sys/commit/1b73967140201b02a8420ee8555ed00a432e97c0, the latter is the latest commit right now and was shown to be the cause:
```
1b73967140201b02a8420ee8555ed00a432e97c0 is the first bad commit
commit 1b73967140201b02a8420ee8555ed00a432e97c0
Author: Andrei Gherzan <andrei@resin.io>
Date:   Mon Sep 3 16:57:46 2018 +0000
    unix: implement SyncFileRange for ARM
    Change-Id: I5a98a732c0e6a229ab93acbce08b4f780f860f72
    GitHub-Last-Rev: 886bffd986fbb7be149e7df3bda65331a74db0b8
    GitHub-Pull-Request: golang/sys#16
    Reviewed-on: https://go-review.googlesource.com/133015
    Reviewed-by: Tobias Klauser <tobias.klauser@gmail.com>
    Run-TryBot: Tobias Klauser <tobias.klauser@gmail.com>
    TryBot-Result: Gobot Gobot <gobot@golang.org>
```

```diff
diff --git a/unix/syscall_linux_arm.go b/unix/syscall_linux_arm.go
index 3ec7a93..fb9b906 100644
--- a/unix/syscall_linux_arm.go
+++ b/unix/syscall_linux_arm.go
@@ -141,6 +141,7 @@ func Fadvise(fd int, offset int64, length int64, advice int) (err error) {
 }
 //sys  mmap2(addr uintptr, length uintptr, prot int, flags int, fd int, pageOffset uintptr) (xaddr uintptr, err error)
+//sys  SyncFileRange(fd int, off int64, n int64, flags int) (err error) = SYS_ARM_SYNC_FILE_RANGE
 func Fstatfs(fd int, buf *Statfs_t) (err error) {
    _, _, e := Syscall(SYS_FSTATFS64, uintptr(fd), unsafe.Sizeof(*buf), uintptr(unsafe.Pointer(buf)))
diff --git a/unix/zsyscall_linux_arm.go b/unix/zsyscall_linux_arm.go
index d29a11c..0231d03 100644
--- a/unix/zsyscall_linux_arm.go
+++ b/unix/zsyscall_linux_arm.go
@@ -2177,6 +2177,16 @@ func mmap2(addr uintptr, length uintptr, prot int, flags int, fd int, pageOffset
 // THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT
+func SyncFileRange(fd int, off int64, n int64, flags int) (err error) {
+   _, _, e1 := Syscall9(SYS_ARM_SYNC_FILE_RANGE, uintptr(fd), 0, uintptr(off), uintptr(off>>32), uintptr(n), uintptr(n>>32), uintptr(flags), 0, 0)
+   if e1 != 0 {
+       err = errnoErr(e1)
+   }
+   return
+}
+
+// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT
+
 func getrlimit(resource int, rlim *rlimit32) (err error) {
    _, _, e1 := RawSyscall(SYS_UGETRLIMIT, uintptr(resource), uintptr(unsafe.Pointer(rlim)), 0)
    if e1 != 0 {
```

Indeed, it calls the function `Syscall9()`, which isn't defined for `linux/arm`...

Please let me know if there's anything I can do to help!

**Comment by fd0** [comment]
CC @tklauser @bradfitz

**Comment by fd0** [comment]
That was... unexpected. But thanks! :)

**Comment by agherzan** [comment]
@fd0 ouch. I'll test and repush.

**Comment by tklauser** [comment]
Thanks @fd0 for reporing and @bradfitz for fixing this so quickly. I didn't test the respective CL locally as I was wrongly assuming the TryBots to be running on `linux/arm`. Sorry about that.

Looking at https://golang.org/cl/133015 again, I noticed that the `sync_file_range2` syscall (for which `arm_sync_file_range` is an alias) has the `flags` argument before the offsets exactly for the reason that there wouldn't be enough registers to pass the arguments otherwise (i.e. we would need to use `Syscall9` in Go instead of `Syscall6`). See https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=edd5cd4a9424f22b0fa08bef5e299d41befd5622 for more information.

This also means that the `SyncFileRange` implementation in `x/sys/unix` and `syscall` is wrong for the `GOARCH`es using `SYS_SYNC_FILE_RANGE2`, namely `ppc64` and `ppc64le`. I'll file a separate issue about this.

**Comment by tklauser** [comment]
@agherzan in case you want to resend a CL adding `SyncFileRange` for `linux/arm`, have a look at https://golang.org/cl/133215 which corrects `SyncFileRange` on `linux/ppc64{,le}`. The implementation for `linux/arm` also has use the argument order for the `SYS_SYNC_FILE_RANGE2` syscall.

**Comment by agherzan** [comment]
Thanks @tklauser . I'll have another go at it. The initial version was tested but I changed it based on the review feedback. Wrong move there.
