### ISSUE TITLE
x/crypto/chacha20poly1305: can't import library with Go 1.8's crypto/tls also linked in

### ISSUE THREAD

**Issue by a13xb** [golang/go#18154]
### What version of Go are you using (`go version`)?
```
go version devel +64969c8 Fri Dec 2 03:31:49 2016 +0000 darwin/amd64
```
### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/alex/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/HEAD-64969c8/libexec"
GOTOOLDIR="/usr/local/Cellar/go/HEAD-64969c8/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/nr/sfqd96m52q76_f0fl1xzr8ch0000gn/T/go-build667867050=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```
### What did you do?
Build a program that
1. performs HTTPS connections with ```net/http```
2. uses ```golang.org/x/crypto/chacha20poly1305``` directly
```
package main

import (
	"golang.org/x/crypto/chacha20poly1305"
	"log"
	"net/http"
)

func E(err error) {
	if err != nil {
		log.Fatal(err)
	}
}

func main() {
	key := make([]byte, chacha20poly1305.KeySize)
	nonce := make([]byte, chacha20poly1305.NonceSize)
	pt := []byte{1, 2, 3}
	log.Printf("plaintext = %x", pt)

	aead, err := chacha20poly1305.New(key)
	E(err)
	out := make([]byte, 0, 100)
	ct := aead.Seal(out[:0], nonce, pt, nil)
	E(err)
	log.Printf("ciphertext = %x", ct)

	pt, err = aead.Open(out[:0], nonce, ct, nil)
	E(err)
	log.Printf("plaintext = %x", pt)

	res, err := http.Get("https://google.com")
	E(err)
	defer res.Body.Close()
	log.Printf("http result = %d", res.StatusCode)
}
```
### What did you expect to see?
The program should compile successfully.
### What did you see instead?
I get this build error:
```
# command-line-arguments
2016/12/02 16:13:53 duplicate symbol polyHashADInternal (types 1 and 1) in golang.org/x/crypto/chacha20poly1305 and /usr/local/Cellar/go/HEAD-64969c8/libexec/pkg/darwin_amd64/vendor/golang_org/x/crypto/chacha20poly1305.a(asm.o)
```
If you comment out the HTTP part, it builds and runs fine (because `net/http` and `crypto/tls` and its vendored dependencies aren't linked).

This was introduced in 77b6a08. The program builds in 1.7.x, so it's a regression. The conflicting symbol is from an assembly file, so I suppose it is because they are not namespaced.
