### ISSUE TITLE
compile: error: shifting a negative signed value.

### ISSUE THREAD

**Issue by meowssir** [golang/go#17183]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
x

### What operating system and processor architecture are you using (`go env`)?
`$ uname -a`
Darwin Byrons-MacBook-Pro-3.local 15.4.0 Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64 x86_64

`$ sysctl -n machdep.cpu.brand_string`
Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz

`$ sw_vers`
ProductName:   	Mac OS X
ProductVersion:	10.11.4
BuildVersion:  	15E65

```
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOROOT="/usr/local/Cellar/go/1.7.1/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.7.1/libexec/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/ml/2nr7wt652n9ddq8yhtxfjzw40000gp/T/go-build066728938=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

### What did you do?
Attempted to build Go 1.4 from source for a certain debugger tool. Following [Installing Go from source](https://golang.org/doc/install/source) guide.
`$ git clone https://go.googlesource.com/go`
`$ cd go`
`$ git checkout go1.4`
`$ cd src`
`$ ./all.bash`

### What did you expect to see?
A successful build.

### What did you see instead?
```
# Building C bootstrap tool.
cmd/dist

# Building compilers and Go bootstrap tool for host, darwin/amd64.
lib9
libbio
liblink
cmd/cc
cmd/gc
cmd/6l
cmd/6a
cmd/6c
/Users/byrongrogan/git/go/src/cmd/6c/txt.c:995:28: error: shifting a negative signed value is undefined [-Werror,-Wshift-negative-value]
/Users/byrongrogan/git/go/src/cmd/6c/txt.c:1045:28: error: shifting a negative signed value is undefined [-Werror,-Wshift-negative-value]
go tool dist: FAILED: clang -Wall -Wstrict-prototypes -Wextra -Wunused -Wno-sign-compare -Wno-missing-braces -Wno-parentheses -Wno-unknown-pragmas -Wno-switch -Wno-comment -Wno-missing-field-initializers -Werror -fno-common -ggdb -pipe -Wuninitialized -O2 -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -mmacosx-version-min=10.6 -c -m64 -I /Users/byrongrogan/git/go/include -I /Users/byrongrogan/git/go/src/cmd/6c -o /Users/byrongrogan/git/go/pkg/obj/cmd/6c/txt.o /Users/byrongrogan/git/go/src/cmd/6c/txt.c
```

**Comment by ianlancetaylor** [comment]
Use `git checkout go1.4.3`, or use a binary download of Go 1.4.

**Comment by davecheney** [comment]
Did you just install xcode8?

Edit cmd/dist and remove the -Werror flag wherever you find it. That'll get
you unblocked.

I've heard that there will be a 1.4.4 to fix the Sierra crash issue, but
there is no ETA so I'd apply this workaround.

**Comment by minux** [comment]
You should try the go1.4.3 tag. It removed -Werror flag.

**Comment by jmhodges** [comment]
Could we get release-branch.go1.4 updated to go1.4.3 then? I've just been using it like I do every release branch.

**Comment by jmhodges** [comment]
Oh, also, there's no go1.4.3 tag. You maybe meant go1.4.2?

**Comment by jmhodges** [comment]
Hm, on what seems to be the latest go1.4.3, I'm not able to get this to compile with clang 8.0.0.

See https://gist.github.com/jmhodges/411d8eadb01457c909d629229e6ff69a

**Comment by ianlancetaylor** [comment]
I think you are running into #16352.
