### ISSUE TITLE
Golang 1.16 undefined variables from main modules.

### ISSUE THREAD

**Issue by enty8080** [golang/go#43377]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16beta1 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/enty8080/Library/Caches/go-build"
GOENV="/Users/enty8080/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/enty8080/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="ios"
GOPATH="/Users/enty8080/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.16beta1"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="0"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/mp/l216mspj1r793n3f2zhh8vg40000gn/T/go-build3642160823=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

```
# go build main.go
```

### What did you expect to see?

Builded file like in 1.15

### What did you see instead?

A lot of undefined variables errors.

**NOTE:** I have `main.go` and `main2.go` where all functions declared and all of them has `package main`. In go 1.15 it builds with success, but go 1.16 can't build it. Why?

**Comment by enty8080** [comment]
Full log of error:

**go 1.15:**

```
enty8080@Ivans-Air zetant-main % ls
fsmanip.go	main.go		transfer.go	utils.go	zetant.go
enty8080@Ivans-Air zetant-main % go build main.go
enty8080@Ivans-Air zetant-main %
```

**go 1.16:**

```
enty8080@Ivans-Air zetant-main % ls
fsmanip.go	main.go		transfer.go	utils.go	zetant.go
enty8080@Ivans-Air zetant-main % go build main.go
# command-line-arguments
./main.go:41:8: undefined: checkTarget
./main.go:53:16: undefined: isError
./main.go:72:22: undefined: getString
./main.go:77:13: undefined: sendString
./main.go:84:20: undefined: getString
./main.go:89:13: undefined: sendString
./main.go:103:17: undefined: sendString
./main.go:105:17: undefined: commandShell
./main.go:109:17: undefined: sendString
./main.go:111:17: undefined: commandCd
./main.go:111:17: too many errors
enty8080@Ivans-Air zetant-main % 
```

**Comment by enty8080** [comment]
It works if `CGO_ENABLED=0`. I think this is not a bug. Closing issue.
