### ISSUE TITLE
cmd/vet: prefix in vet output breaks error file format compatibility

### ISSUE THREAD

**Issue by mirza-s** [golang/go#34142]
### What version of Go are you using (`go version`)?
<pre>
$ go version
go version go1.13 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/Users/mbp/go/bin"
GOCACHE="/Users/mbp/Library/Caches/go-build"
GOENV="/Users/mbp/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY="github.com/mirza-s"
GONOSUMDB="github.com/mirza-s"
GOOS="darwin"
GOPATH="/Users/mbp/go"
GOPRIVATE="github.com/mirza-s"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/nt/0hzfppd92jvbk99fhvnhy8ph0000gn/T/go-build729502798=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Run
```
go vet cmd/main.go
```

### What did you expect to see?
```
cmd/main.go:187:62: undefined: a
```

### What did you see instead?
```
vet: cmd/main.go:187:62: undeclared name: a
```

This appears to be introduced in 38431f1044880b936e35034ded19a6a8bc9faa21

**Comment by toothrot** [comment]
Hi @mirza-s,

I can confirm this output change locally:
```go
# vet.go
package main

import "fmt"

func main() {
	fmt.Println(a)
}
```

```bash
$ go1.12 vet ./vet.go
# command-line-arguments [command-line-arguments.test]
./vet.go:6:14: undefined: a

$ go vet ./vet.go
# command-line-arguments
vet: ./vet.go:6:14: undeclared name: a

$ go build ~/vet.go 
# command-line-arguments
./vet.go:6:14: undefined: a
```

I'm not sure if this is a feature or a bug. 

/cc @rsc, @josharian and @bradfitz, who have context on the CLs for #31916
