### ISSUE TITLE
x/net/http2: 

### ISSUE THREAD

**Issue by RobHumphris** [golang/go#45950]
### What version of Go are you using (`go version`)?

<pre>
go version go1.14 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Caused by the latest release. `golang.org/x/net v0.0.0-20210504132125-bbd867fde50d`

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/rob/.cache/go-build"
GOENV="/home/rob/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY="github.com/8power,github.com/RobHumphris"
GONOSUMDB="github.com/8power,github.com/RobHumphris"
GOOS="linux"
GOPATH="/mnt/c/Users/User/go"
GOPRIVATE="github.com/8power,github.com/RobHumphris"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/mnt/c/Users/User/go/src/data-reprocessing/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build056882833=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

Updated my dependencies in order to bring in a new version of a module used elsewhere in my project.

### What did you expect to see?

`go get` to get the modules as per usual.

### What did you see instead?
```
# golang.org/x/net/http2
../../pkg/mod/golang.org/x/net@v0.0.0-20210504132125-bbd867fde50d/http2/transport.go:598:14: undefined: tls.Dialer
note: module requires Go 1.17
```
I need to stick with the version of Go that I have as I am deploying a lot of Go based Google Cloud Functions - and thats pegged at v1.13.

**Comment by ALTree** [comment]
Dup of #45946.

**Comment by ianlancetaylor** [comment]
Since this came up five times in 24 hours, I went ahead and patches golang.org/x/net so that it will work with versions of Go before 1.15.  That should fix this problem.  I still strongly encourage everyone to upgrade to a supported version of Go, and I do not promise that this will not break again in the future.

**Comment by RobHumphris** [comment]
> Since this came up five times in 24 hours, I went ahead and patches golang.org/x/net so that it will work with versions of Go before 1.15. That should fix this problem. I still strongly encourage everyone to upgrade to a supported version of Go, and I do not promise that this will not break again in the future.

Thank-you for this, I would love to upgrade but have my code in 14 different Google Cloud Functions - which is stuck at version 1.13 so I cannot upgrade until Google do.

**Comment by rsc** [comment]
FWIW we are aware of GCE and GCF not yet supporting Go 1.16. I am hopeful that they will by mid-summer. Apologies for the slow rollout there.
