### ISSUE TITLE
playground: Javascript error on "Share" button

### ISSUE THREAD

**Issue by calmh** [golang/go#18982]
Hitting "Share" on the playground currently does nothing. In the Javascript console, the following is printed:

```
[Error] TypeError: shareCallbacks[i] is not a function. (In 'shareCallbacks[i](url)', 'shareCallbacks[i]' is an instance of Object)
	complete (playground.js:419)
	k (jquery.min.js:2:16926)
	fireWith (jquery.min.js:2:17709)
	y (jquery.min.js:2:80937)
	d (jquery.min.js:2:86376)
```

Latest Safari and Chrome on Mac.

To reproduce, just open https://play.golang.org/ and click "Share". Expected result is that a share URL pops up. Actual result is no share URL.

**Comment by cespare** [comment]
I see this too (Chrome on Linux). Presumably caused by 69cfa789611bdb3e17152c1e81fc4a5a8bfcf863 (see also #15378).

**Comment by LionNatsu** [comment]
I can't see this. It works fine here, Chrome 55 on Linux.

**Comment by calmh** [comment]
It seems fixed now, but was certainly the case for a while. I'll leave this for maintainers to close, if there is something around caching or similar that maybe should be looked at as a result of this.

**Comment by ianlancetaylor** [comment]
@broady You fixed this, right?

**Comment by minux** [comment]
Fixed by https://golang.org/cl/36488/
