### ISSUE TITLE
cmd/cgo: variadic parameters not working with C.char 

### ISSUE THREAD

**Issue by duzy** [golang/go#25143]
### What version of Go are you using (`go version`)?

```shell
$ go version
go version go1.10.1 linux/amd64
```

### Does this issue reproduce with the latest release?

I think so.

### What operating system and processor architecture are you using (`go env`)?

I'm working with alpine 3.7.

```sh
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
```

### What did you do?

Working with this segment:

```go
func cfree(cs... *C.char) {
    for _, s := range cs {
        C.free(unsafe.Pointer(s))
    }
}
```

### What did you expect to see?

Nothing as all good.

### What did you see instead?

Compilation error as "undefined: C in C.char".

**Comment by cznic** [comment]
Missing `import "C"`? Please show a complete program.

**Comment by cznic** [comment]
I can reproduce the issue with the above code in Go1.10. I don't know why it fails. I seem to recall, that Go cannot call C variadic functions but I cannot find that mentioned in the CGO docs at https://golang.org/cmd/cgo/.

However, in this case `free` is not a C function and I don't see why it should not compile.

**Comment by AlexRouSg** [comment]
cc @ianlancetaylor

**Comment by odeke-em** [comment]
>I seem to recall, that Go cannot call C variadic functions but I cannot find that mentioned in the CGO docs at

@cznic is this the issue that you are looking for https://github.com/golang/go/issues/975?
https://github.com/golang/go/issues/23537 was filed to document this but the CL https://go-review.googlesource.com/#/c/90415/ hasn't yet been reviewed.

**Comment by odeke-em** [comment]
Although perhaps this is an entirely different issue. #975 is about calling variadic C functions in Go, while this is one is entirely failing when a Go function has a variadic C.<type> signature.

/cc @hirochachacha too

**Comment by duzy** [comment]
Thank you all guys for addressing this issue. Looking forward to using Go1.11 instead. Cheers!
