### ISSUE TITLE
website: inconsistency in supported OS X versions

### ISSUE THREAD

**Issue by 0xmohit** [golang/go#16625]
https://golang.org/dl/ mentions:

> Apple OS X
> OS X 10.8 or later, Intel 64-bit processor

https://golang.org/doc/install says:

> Official binary distributions are available for ...
> Mac OS X (10.7 and above)

**Comment by bradfitz** [comment]
And later down the page, it says the requirements for compiling from source are "Mac OS X 10.7 or later".

I seem to recall that 10.7 is the minimum requirement for building for source, but somehow the binaries we produce (or the packaging) requires 10.8. I forget the details. @adg?

But the first mistake you cited is easy to fix at least.

**Comment by bradfitz** [comment]
I kept this bug open (using "Updates" in the commit message) so we can figure out what the story with source vs binary release supported versions is on OS X. I was waiting for @adg.

**Comment by quentinmit** [comment]
Okay, I'll tag this for 1.7 then, hopefully we can get the docs right before we release.

**Comment by adg** [comment]
I don't remember anymore.
I guess we'll have to test it to make sure.

**Comment by bradfitz** [comment]
I'll try a build on OS X 10.7 and see what happens.

**Comment by bradfitz** [comment]
Just tried OS X 10.7. It doesn't even compile:

```
crypto/x509
# crypto/x509
crypto/x509/root_cgo_darwin.go: In function 'FetchPEMRoots':
crypto/x509/root_cgo_darwin.go:97: error: 'for' loop initial declaration used outside C99 mode
crypto/x509/root_cgo_darwin.go:106: error: 'for' loop initial declaration used outside C99 mode
crypto/x509/root_cgo_darwin.go:114: error: 'SecCertificateCopyNormalizedSubjectContent' is unavailable (declared at /System/Library/Frameworks/Security.framework/Headers/SecCertificate.h:460)
crypto/x509/root_cgo_darwin.go:119: error: 'SecCertificateCopyNormalizedIssuerContent' is unavailable (declared at /System/Library/Frameworks/Security.framework/Headers/SecCertificate.h:443)
database/sql/driver
database/sql
encoding
```

I'm sure we can work around it, but there's no point. And we don't want to run builders for OS X 10.{7,8,9,10,11,12}. Too many. 8 is old enough. Plus I still recall that 7 (Lion) leaked pipes in exec or something.

I'll fix the docs.
