### ISSUE TITLE
runtime/race: change in 93a4f03 leads to a failed build on Amazon Linux 2 and arm64

### ISSUE THREAD

**Issue by alexey-tsvetnov** [golang/go#78573]
### Go version

1.25.9

### What did you do?

It seems [this commit](https://github.com/golang/go/commit/93a4f03ed88caaa513229982f34f27b30c620d27) causes 1.25.9 builds to fail on Amazon Linux 2 on arm64.

**TL;DR**: I've taken `race_linux_arm64.syso` from 1.25.8 and got a working build.

There are multiple complains about undefined symbols:

```
$ sed -n "s/\(^.*\)\(undefined reference to.*\(__.*\)'$\)/\3/p" build.log | sort | uniq
__aarch64_cas4_sync
__aarch64_cas8_sync
__aarch64_ldadd4_sync
__aarch64_ldadd8_sync
__aarch64_ldclr4_sync
__aarch64_ldclr8_sync
__aarch64_ldset4_sync
__aarch64_ldset8_sync
__aarch64_swp1_sync
__aarch64_swp4_sync
__aarch64_swp8_sync
``` 

Amazon Linux 2 is shipped with gcc 7, glibc 2.26, binutils 2.29.1
However, with gcc10 it builds, race detection tests pass but `TestElfBindNow` test fails

```
--- FAIL: TestElfBindNow (1.92s)
    --- FAIL: TestElfBindNow/bindnow-pie-linkmode-external (0.54s)
        elf_test.go:389: test .dynamic: "bindnow-pie-linkmode-external" section not in readonly segment
        elf_test.go:391: section .dynamic location: st=0x12fbf0 en=0x12fe00
        elf_test.go:393: sec .dynamic found in these segments: 
        elf_test.go:395:  "PT_LOAD"
        elf_test.go:395:  "PT_DYNAMIC"
        elf_test.go:395:  "PT_GNU_RELRO"
        elf_test.go:397: 
            all segments: 
        elf_test.go:399: 0 t=PT_PHDR fl=PF_R st=0x40 en=0x270
        elf_test.go:399: 1 t=PT_INTERP fl=PF_R st=0x270 en=0x28b
        elf_test.go:399: 2 t=PT_LOAD fl=PF_X+PF_R st=0x0 en=0xa5818
        elf_test.go:399: 3 t=PT_LOAD fl=PF_W+PF_R st=0xc3e00 en=0x133dea
        elf_test.go:399: 4 t=PT_DYNAMIC fl=PF_W+PF_R st=0x12fbf0 en=0x12fe00
        elf_test.go:399: 5 t=PT_NOTE fl=PF_R st=0x28c en=0x334
        elf_test.go:399: 6 t=PT_GNU_EH_FRAME fl=PF_R st=0xa56dc en=0xa5818
        elf_test.go:399: 7 t=PT_GNU_STACK fl=PF_W+PF_R st=0x0 en=0x0
        elf_test.go:399: 8 t=PT_TLS fl=PF_R st=0xc3e00 en=0xc3e00
        elf_test.go:399: 9 t=PT_GNU_RELRO fl=PF_W+PF_R st=0xc3e00 en=0x130000
        elf_test.go:402: test bindnow-pie-linkmode-external failed
FAIL
FAIL	cmd/link/internal/ld	4.898s
```

### What did you see happen?

Errors look like 

```
# go tool dist test -run=^encoding/gob:race$
# encoding/gob.test
/builddir/build/BUILD/go/pkg/tool/linux_arm64/link: running gcc failed: exit status 1
/usr/bin/gcc -s -Wl,--build-id=0x0b249f71dab12643d751f9c25392f3cdc93db3e1 -o $WORK/b001/gob.test -rdynamic -Wl,--compress-debug-sections=zlib /tmp/go-link-2698906647/go.o /tmp/go-link-2698906647/000000.o /tmp/go-link-2698906647/000001.o /tmp/go-link-2698906647/000002.o /tmp/go-link-2698906647/000003.o /tmp/go-link-2698906647/000004.o /tmp/go-link-2698906647/000005.o /tmp/go-link-2698906647/000006.o /tmp/go-link-2698906647/000007.o /tmp/go-link-2698906647/000008.o /tmp/go-link-2698906647/000009.o /tmp/go-link-2698906647/000010.o /tmp/go-link-2698906647/000011.o /tmp/go-link-2698906647/000012.o /tmp/go-link-2698906647/000013.o /tmp/go-link-2698906647/000014.o /tmp/go-link-2698906647/000015.o /tmp/go-link-2698906647/000016.o /tmp/go-link-2698906647/000017.o /tmp/go-link-2698906647/000018.o /tmp/go-link-2698906647/000019.o /tmp/go-link-2698906647/000020.o /tmp/go-link-2698906647/000021.o /tmp/go-link-2698906647/000022.o -O2 -g -lresolv -O2 -g -lpthread -O2 -g -no-pie
/tmp/go-link-2698906647/000022.o: In function `__sanitizer::DecreaseTotalMmap(unsigned long)':
gotsan.cpp:(.text+0x12ec): undefined reference to `__aarch64_ldadd8_sync'
/tmp/go-link-2698906647/000022.o: In function `__sanitizer_acquire_crash_state':
gotsan.cpp:(.text+0x1324): undefined reference to `__aarch64_swp1_sync'
```

### What did you expect to see?

No undefined references.

**Comment by sfc-gh-jzana** [comment]
Hitting the same issue when upgrading from 1.26.1 to 1.26.2.

**Comment by alexey-tsvetnov** [comment]
@sfc-gh-jzana , what's your build environment (os, gcc)?

**Comment by sfc-gh-jzana** [comment]
@alexey-tsvetnov Rocky Linux 9.7 on Amazon Linux 2 kernel version 5.10.245-241.978.amzn2.x86_64.

In terms of compiler, I am using the hermetic c/c++ compiler from bazel.

Here's the exact error I get:
```
     ERROR: /home/repo/snapps/pep/server/main/BUILD.bazel:21:10: GoLink pep/server/main/pep_/pep failed: (Exit 1): builder failed: error executing GoLink command (from target //pep/server/main:pep)          
       (cd /scratch/bazel/226ebe59666fa2603f9b789585dec1f0/sandbox/linux-sandbox/2045/execroot/_main &amp;&amp; \                                                                                              
       exec env - \                                                                                                                                                                                            
         CC=external/hermetic_cc_toolchain~~toolchains~zig_config/tools/aarch64-linux-gnu.2.17/c++ \                                                                                                           
         CGO_ENABLED=1 \                                                                                                                                                                                       
         GOARCH=arm64 \                                                                                                                                                                                        
         GODEBUG='winsymlink=0' \                                                                                                                                                                              
         GOEXPERIMENT=boringcrypto \                                                                                                                                                                           
         GOOS=linux \                                                                                                                                                                                          
         GOPATH='' \                                                                                                                                                                                           
         GOROOT=bazel-out/k8-fastbuild-ST-de7c7d151f14/bin/external/rules_go~/stdlib_ \                                                                                                                        
         GOROOT_FINAL=GOROOT \                                                                                                                                                                                 
         GOTOOLCHAIN=local \                                                                                                                                                                                   
         PATH=external/hermetic_cc_toolchain~~toolchains~zig_config/tools/aarch64-linux-gnu.2.17:external/hermetic_cc_toolchain~~toolchains~zig_config/tools:/bin:/usr/bin \                                   
       bazel-out/k8-opt-exec-ST-ce2512320804/bin/external/rules_go~~go_sdk~main___download_0/builder_reset/builder '-param=bazel-out/k8-fastbuild-ST-33b8d35157f6/bin/pep/server/main/pep_/pep-0.params' --    
     -extar external/hermetic_cc_toolchain~~toolchains~zig_config/tools/ar -race -extld external/hermetic_cc_toolchain~~toolchains~zig_config/tools/aarch64-linux-gnu.2.17/c++ -linkmode external              
     '-buildid=redacted' -s -w -extldflags '-fno-lto -fsanitize-undefined-strip-path-components=-1')                                                                                                           
     # Configuration: 5886c8915df9e21672f0215f726dab2bb8eabef6f59f22ba35cca2f078f753c1                                                                                                                         
     # Execution platform: @@rules_gcbi~//platforms:linux-x86_64                                                                                                                                               
                                                                                                                                                                                                               
     Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging                                                                                              
     external/rules_go~~go_sdk~main___download_0/pkg/tool/linux_amd64/link: running /tmp/3077835856/builder-cc failed: exit status 1                                                                           
     /tmp/3077835856/builder-cc -s -Wl,-z,relro -pie -Wl,--build-id=0x498919aff001d8366249403a2544fba2d833084f -o bazel-out/k8-fastbuild-ST-33b8d35157f6/bin/pep/server/main/pep_/pep -rdynamic                
     -Qunused-arguments -Wl,--compress-debug-sections=zlib /tmp/go-link-3114706050/go.o /tmp/go-link-3114706050/000000.o /tmp/go-link-3114706050/000001.o /tmp/go-link-3114706050/000002.o                     
     /tmp/go-link-3114706050/000003.o /tmp/go-link-3114706050/000004.o /tmp/go-link-3114706050/000005.o /tmp/go-link-3114706050/000006.o /tmp/go-link-3114706050/000007.o /tmp/go-link-3114706050/000008.o     
     /tmp/go-link-3114706050/000009.o /tmp/go-link-3114706050/000010.o /tmp/go-link-3114706050/000011.o /tmp/go-link-3114706050/000012.o /tmp/go-link-3114706050/000013.o /tmp/go-link-3114706050/000014.o     
     /tmp/go-link-3114706050/000015.o /tmp/go-link-3114706050/000016.o /tmp/go-link-3114706050/000017.o /tmp/go-link-3114706050/000018.o /tmp/go-link-3114706050/000019.o /tmp/go-link-3114706050/000020.o     
     /tmp/go-link-3114706050/000021.o /tmp/go-link-3114706050/000022.o /tmp/go-link-3114706050/000023.o /tmp/go-link-3114706050/000024.o /tmp/go-link-3114706050/000025.o /tmp/go-link-3114706050/000026.o     
     /tmp/go-link-3114706050/000027.o /tmp/go-link-3114706050/000028.o /tmp/go-link-3114706050/000029.o /tmp/go-link-3114706050/000030.o /tmp/go-link-3114706050/000031.o /tmp/go-link-3114706050/000032.o     
     /tmp/go-link-3114706050/000033.o /tmp/go-link-3114706050/000034.o /tmp/go-link-3114706050/000035.o /tmp/go-link-3114706050/000036.o /tmp/go-link-3114706050/000037.o /tmp/go-link-3114706050/000038.o     
     -fno-lto -fsanitize-undefined-strip-path-components=-1 -pthread -lresolv -fno-lto -fsanitize-undefined-strip-path-components=-1 -pthread -pthread -fno-lto -fsanitize-undefined-strip-path-components=-1  
     -ldl -pthread -fno-lto -fsanitize-undefined-strip-path-components=-1 -pthread -lpthread -fno-lto -fsanitize-undefined-strip-path-components=-1 -pthread -fno-lto                                          
     -fsanitize-undefined-strip-path-components=-1 -pthread -fno-lto -fsanitize-undefined-strip-path-components=-1                                                                                             
     ld.lld: error: undefined symbol: __aarch64_ldadd8_sync                                                                                                                                                    
```

followed by a bunch more undefined symbols.

Again, my bazel build works fine on 1.26.1, and fails on 1.26.2

**Comment by sfc-gh-jzana** [comment]
Still seeing the same issue on 1.26.3.  How do we get a fix prioritized?

**Comment by randall77** [comment]
I don't think anyone understands what is going on here.

In your build failure log, it is calling the system linker. I don't see the actual .syso on the command line for the system linker. Can you grab what the system linker command line looks like when successfully building with the 1.25 syso?

**Comment by alexey-tsvetnov** [comment]
@randall77 , from what I see here, most people who have this issue, either disable `-race` or override `race_linux_arm64.syso` from 1.25.8

What exactly you need to troubleshoot the issue?

**Comment by randall77** [comment]
I would like to see this line from a successful build log:
```
/tmp/3077835856/builder-cc -s -Wl,-z,relro -pie -Wl,--build-id=0x498919aff001d8366249403a2544fba2d833084f -o bazel-out/k8-fastbuild-ST-33b8d35157f6/bin/pep/server/main/pep_/pep -rdynamic                
     -Qunused-arguments -Wl,--compress-debug-sections=zlib /tmp/go-link-3114706050/go.o /tmp/go-link-3114706050/000000.o /tmp/go-link-3114706050/000001.o /tmp/go-link-3114706050/000002.o                     
     /tmp/go-link-3114706050/000003.o /tmp/go-link-3114706050/000004.o /tmp/go-link-3114706050/000005.o /tmp/go-link-3114706050/000006.o /tmp/go-link-3114706050/000007.o /tmp/go-link-3114706050/000008.o     
     /tmp/go-link-3114706050/000009.o /tmp/go-link-3114706050/000010.o /tmp/go-link-3114706050/000011.o /tmp/go-link-3114706050/000012.o /tmp/go-link-3114706050/000013.o /tmp/go-link-3114706050/000014.o     
     /tmp/go-link-3114706050/000015.o /tmp/go-link-3114706050/000016.o /tmp/go-link-3114706050/000017.o /tmp/go-link-3114706050/000018.o /tmp/go-link-3114706050/000019.o /tmp/go-link-3114706050/000020.o     
     /tmp/go-link-3114706050/000021.o /tmp/go-link-3114706050/000022.o /tmp/go-link-3114706050/000023.o /tmp/go-link-3114706050/000024.o /tmp/go-link-3114706050/000025.o /tmp/go-link-3114706050/000026.o     
     /tmp/go-link-3114706050/000027.o /tmp/go-link-3114706050/000028.o /tmp/go-link-3114706050/000029.o /tmp/go-link-3114706050/000030.o /tmp/go-link-3114706050/000031.o /tmp/go-link-3114706050/000032.o     
     /tmp/go-link-3114706050/000033.o /tmp/go-link-3114706050/000034.o /tmp/go-link-3114706050/000035.o /tmp/go-link-3114706050/000036.o /tmp/go-link-3114706050/000037.o /tmp/go-link-3114706050/000038.o     
     -fno-lto -fsanitize-undefined-strip-path-components=-1 -pthread -lresolv -fno-lto -fsanitize-undefined-strip-path-components=-1 -pthread -pthread -fno-lto -fsanitize-undefined-strip-path-components=-1  
     -ldl -pthread -fno-lto -fsanitize-undefined-strip-path-components=-1 -pthread -lpthread -fno-lto -fsanitize-undefined-strip-path-components=-1 -pthread -fno-lto                                          
     -fsanitize-undefined-strip-path-components=-1 -pthread -fno-lto -fsanitize-undefined-strip-path-components=-1                                                                                             
     ld.lld: error: undefined symbol: __aarch64_ldadd8_sync                                                                                                                                                    
```
All the arguments to `builder-cc`.
Not sure if that would help me any, kinda grasping at straws.

**Comment by alexey-tsvetnov** [comment]
But I'm not using Bazel...

**Comment by randall77** [comment]
Ah, you're not the OP.

I want to see a log of your failing build then. Particularly, whatever your linker command line looks like.
Both for the failing build and a successful build, if possible.

**Comment by alexey-tsvetnov** [comment]
@randall77 , I've just sent it to you by email, the successful full build log, so you have a complete picture.
I'm also trying to find a failed build

**Comment by alexey-tsvetnov** [comment]
@randall77 , I started a new clean Go1.25.9 build with the original source and no replacements, and it apparently failed again. 
A full build log is also sent by email

**Comment by randall77** [comment]
It looks like the _sync versions of those methods are new. Those are the ones that are missing.
```
khr@Mac-Studio ~ % nm go1.25.7/src/runtime/race/race_linux_arm64.syso | grep aarch64
                 U __aarch64_cas4_acq_rel
                 U __aarch64_cas8_acq_rel
                 U __aarch64_ldadd4_acq_rel
                 U __aarch64_ldadd8_acq_rel
                 U __aarch64_ldclr4_acq_rel
                 U __aarch64_ldclr8_acq_rel
                 U __aarch64_ldset4_acq_rel
                 U __aarch64_ldset8_acq_rel
                 U __aarch64_swp1_acq
                 U __aarch64_swp4_acq
                 U __aarch64_swp8_acq
khr@Mac-Studio ~ % nm go1.26.1/src/runtime/race/race_linux_arm64.syso | grep aarch64
                 U __aarch64_cas4_acq_rel
                 U __aarch64_cas8_acq_rel
                 U __aarch64_ldadd4_acq_rel
                 U __aarch64_ldadd8_acq_rel
                 U __aarch64_ldclr4_acq_rel
                 U __aarch64_ldclr8_acq_rel
                 U __aarch64_ldset4_acq_rel
                 U __aarch64_ldset8_acq_rel
                 U __aarch64_swp1_acq
                 U __aarch64_swp4_acq
                 U __aarch64_swp8_acq
khr@Mac-Studio ~ % nm go1.26.2/src/runtime/race/race_linux_arm64.syso | grep aarch64
                 U __aarch64_cas4_acq_rel
                 U __aarch64_cas4_sync
                 U __aarch64_cas8_acq_rel
                 U __aarch64_cas8_sync
                 U __aarch64_ldadd4_sync
                 U __aarch64_ldadd8_sync
                 U __aarch64_ldclr4_sync
                 U __aarch64_ldclr8_sync
                 U __aarch64_ldset4_sync
                 U __aarch64_ldset8_sync
                 U __aarch64_swp1_sync
                 U __aarch64_swp4_sync
                 U __aarch64_swp8_sync
```
I suspect this was due to us building the syso with a more recent version of gcc, which expects those _sync functions to be in libc (or some other system library? Not sure).

So maybe we need to build the syso with an older gcc, or in some compatibility mode. It would help verify this theory if you could upgrade your gcc and see if the problem goes away.

**Comment by alexey-tsvetnov** [comment]
With newer gcc all is good. I build Golang for Amazon Linux 2023 with gcc11 - no issues.
I've also got successful builds with gcc 15 and 16.
 
However, as I initially mentioned, Amazon Linux 2 is shipped with gcc 7 and glibc 2.26
We cannot change it, it's pretty old Linux distribution. But it's still supported and used on a very large number of instances.

**Comment by randall77** [comment]
Ok, that's useful info. I don't think it was intentional to upgrade the min required gcc. Maybe we could undo it, but I'm not sure. The build process for the syso race files is a bit finicky already, throwing an older gcc into the mix is only going to make that worse.

**Comment by alexey-tsvetnov** [comment]
Thank you for looking into this issue!
I'd highly appreciate if such a task of rebuilding syso file with gcc 7 got assigned and prioritized.
Otherwise, we'd stuck with the version from 1.25.8

**Comment by randall77** [comment]
@gopherbot Please open a backport issue for 1.26.

**Comment by randall77** [comment]
@alexey-tsvetnov 
If you could try the syso in the above CL and see if it works for you on your old gcc system, that would be great.

**Comment by alexey-tsvetnov** [comment]
@randall77 ,
Absolutely! I can't wait to see the results.
Thank you for working on this issue!

**Comment by alexey-tsvetnov** [comment]
@randall77 , It works!!! 
Thank you so much for fixing it :)

**Comment by prattmic** [comment]
@randall77 This will need a 1.25 backport as well, since we backported the bad syso to 1.25 as well: #78086.

**Comment by alexey-tsvetnov** [comment]
@randall77 
Yes, a backport to 1.25 is absolutely crucial. 
At Amazon Linux, currently, we ship -1 release, meaning 1.25.*
