### ISSUE TITLE
cgo: macOS unable to load c++ standard libraries in header files

### ISSUE THREAD

**Issue by joesonw** [golang/go#35031]
### What version of Go are you using (`go version`)?
<pre>
$ go version
go version go1.13 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/Joesonw/Library/Caches/go-build"
GOENV="/Users/Joesonw/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/Joesonw/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.13/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.13/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/Users/Joesonw/go/github.com/joesonw/js8/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/b4/t4v6zpln4rb16cvg747dz3j80000gn/T/go-build124603914=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

For any CGO project, have following code (any c++ library) in `header` files
```
#include <iostream>
```

The exact same project compiles under Debian

### What did you expect to see?

Compile smoothly

### What did you see instead?

`fatal error: 'iostream' file not found`

**Comment by andybons** [comment]
Can you provide a more complete reproduction? Thanks.

**Comment by ianlancetaylor** [comment]
This looks like a problem with your C++ compiler, not with Go.  What happens if you write a tiny x.cc file that says `#include <iostream>` and run `g++ -c x.cc`?

**Comment by joesonw** [comment]
It was outdated clang. after upgrading clang to 11, it now compiles.

**Comment by joesonw** [comment]
> This looks like a problem with your C++ compiler, not with Go. What happens if you write a tiny x.cc file that says `#include <iostream>` and run `g++ -c x.cc`?

I tried it with g++ and clang++,  I even tried gcc. all worked fine.

**Comment by ianlancetaylor** [comment]
If this is still a problem for you, please show us exactly how to reproduce the problem.  Please also include the output of `go build -x`.  Thanks.

**Comment by joesonw** [comment]
@iamoryanmoshe https://gist.github.com/joesonw/bfd4dbd0b34b42f5f4941502633f1bb0 and you simply comple it by `go build x.go`, this will give `./x.h:1:10: fatal error: 'iostream' file not found` error. 

By referencing `x.h` along in a `.cc` file would compile thought. 

I suspect It has to do with how cgo calls c/c++ compiler on macOS ?

**Comment by ianlancetaylor** [comment]
Oh, sorry for not noticing, but `<iostream>` is C++.  The cgo tool only supports C.  You can't `#include` a C++ header file using cgo.
