### ISSUE TITLE
affected/package: golang.org/x/mobile/bind/java

### ISSUE THREAD

**Issue by dpanic** [golang/go#58426]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GOHOSTARCH="amd64" 
GOHOSTOS="linux"   

ANDROID_NDK_HOME=/home/dpanic/development/Android/Sdk/ndk/25.2.9519653
ANDROID_HOME=/home/dpanic/development/Android/Sdk
</pre></details>

### What did you do?
Binding Go Mobile project with following command:

```
CGO_ENABLED=1 \
        gomobile bind \
        -androidapi 23 \
        -target=android/$TARGET \
        -ldflags="-w -s" \
        -o export_$TARGET.aar \
        -v
```

### What did you expect to see?
On Go version 1.19.5 and lower this works.

### What did you see instead?
```
unable to import bind/java: [-: # golang.org/x/mobile/bind/java                         
/home/dpanic/go/pkg/mod/golang.org/x/mobile@v0.0.0-20221110043201-43a038452099/bind/java
/context_android.go:9:10: fatal error: jni.h: No such file or directory                 
    9 | //#include <jni.h>                                                              
      |          ^~~~~~~                                                                
compilation terminated.]                                                                
gomobile: /home/dpanic/go/bin/gobind -lang=go,java -outdir=/tmp/gomobile-work-1953076754
 example.com/export failed: exit status 1                                            
```

**Comment by dr2chase** [comment]
@hyangah can you give this a look?  It has a real "this could be a lot of things" look to it.

**Comment by hyangah** [comment]
Is it possible to post the log when running gomobile bind with `-x -v` flags?

**Comment by dpanic** [comment]
```
GOMOBILE=/home/dpanic/go/pkg/gomobile
WORK=/tmp/gomobile-work-791525417
GOOS=android CGO_ENABLED=1 $GOPATH/bin/gobind -lang=go,java -outdir=$WORK REDACTED.com/export
unable to import bind/java: [-: # golang.org/x/mobile/bind/java
/home/dpanic/go/pkg/mod/golang.org/x/mobile@v0.0.0-20221110043201-43a038452099/bind/java/context_android.go:9:10: fatal error: jni.h:
No such file or directory
    9 | //#include <jni.h>
      |          ^~~~~~~
compilation terminated.]
rm -r -f "$WORK"
gomobile: /home/dpanic/go/bin/gobind -lang=go,java -outdir=/tmp/gomobile-work-791525417 REDACTED.com/export failed: exit status 1

```

**Comment by leo-lox** [comment]
had the same issue for me the environment variable in PATH => `C:\Program Files\OpenJDK\jdk-19.0.2\bin` was missing.
+ make sure to run `gomobile init` again

**Comment by dpanic** [comment]
```gomobile init``` solves the problem!

Thank you @leo-lox

**Comment by ChenSee** [comment]
When encountering the same problem, gomobile init does not solve the problem.

**Comment by yiitz** [comment]
finally solved by upgrade golang.org/x/mobile to latest version.
`go get -u golang.org/x/mobile`

**Comment by chenxiaolong** [comment]
After doing a git bisect, this seems to happen when using go 1.20 with a version of gomobile that's missing https://github.com/golang/mobile/commit/406ed3a7b8e44dc32844953647b49696d8847d51. Relevant bug report: https://github.com/golang/go/issues/56292.

(For folks who are using the gomobile version distributed in the Fedora repositories, I created a bug report to get that updated at: https://bugzilla.redhat.com/show_bug.cgi?id=2209147)

**Comment by ignoramous** [comment]
icymi: `gomobile` works on [go1.21](https://go.dev/doc/go1.21) just fine.

**Comment by vikulin** [comment]
Any updates? It is still reproducing for golang v1.21.11 and v1.22.4

**Comment by yiitz** [comment]
> Any updates? It is still reproducing for golang v1.21.11 and v1.22.4

I solved it after update my project's go mobile dependencies to the latest version.

**Comment by vikulin** [comment]
@yiitz could you please give exact golang, gomobile versions where you have solved this issue for?

**Comment by ignoramous** [comment]
> could you please give exact golang, gomobile versions where you have solved this issue for?

Works with latest.

You can see [this Action](https://github.com/celzero/firestack/blob/b9e9dcd6796afe4ff036f254d671531f4ae8ac0d/.github/workflows/go.yml) [recent run](https://github.com/celzero/firestack/actions/runs/9531658646/job/26272825170) which builds AAR (Android Archive) with go1.22 just fine ([gomobile install/init in Makefile](https://github.com/celzero/firestack/blob/b9e9dcd6796afe4ff036f254d671531f4ae8ac0d/Makefile#L53) via [make-aar](https://github.com/celzero/firestack/blob/b9e9dcd6796afe4ff036f254d671531f4ae8ac0d/make-aar#L64)).

**Comment by vikulin** [comment]
> > could you please give exact golang, gomobile versions where you have solved this issue for?
> 
> Works with latest.
> 
> You can see [this Action](https://github.com/celzero/firestack/blob/b9e9dcd6796afe4ff036f254d671531f4ae8ac0d/.github/workflows/go.yml) ([recent run](https://github.com/celzero/firestack/actions/runs/9531658646/job/26272825170)) which builds AAR (Android Archive) with go1.22 just fine ([gomobile install/init in Makefile](https://github.com/celzero/firestack/blob/b9e9dcd6796afe4ff036f254d671531f4ae8ac0d/Makefile#L53) via [make-aar](https://github.com/celzero/firestack/blob/b9e9dcd6796afe4ff036f254d671531f4ae8ac0d/make-aar#L64)).

I like your 🐼 symbols)

**Comment by vikulin** [comment]
> > could you please give exact golang, gomobile versions where you have solved this issue for?
> 
> Works with latest.
> 
> You can see [this Action](https://github.com/celzero/firestack/blob/b9e9dcd6796afe4ff036f254d671531f4ae8ac0d/.github/workflows/go.yml) ([recent run](https://github.com/celzero/firestack/actions/runs/9531658646/job/26272825170)) which builds AAR (Android Archive) with go1.22 just fine ([gomobile install/init in Makefile](https://github.com/celzero/firestack/blob/b9e9dcd6796afe4ff036f254d671531f4ae8ac0d/Makefile#L53) via [make-aar](https://github.com/celzero/firestack/blob/b9e9dcd6796afe4ff036f254d671531f4ae8ac0d/make-aar#L64)).

Arr builds successfully has been [done ](https://github.com/RiV-chain/RiV-mesh/actions/runs/9546535926/job/26309622453) in GitHub Action but still failing in local environment:
```
Executing make

gomobile: /usr/bin/gobind -lang=go,java -outdir=/tmp/gomobile-work-1766811808 -tags=mobile github.com/RiV-chain/RiV-mesh/contrib/mobile github.com/RiV-chain/RiV-mesh/src/config failed: exit status 1
unable to import bind/java: [-: # golang.org/x/mobile/bind/java
/home/vadym/go/pkg/mod/golang.org/x/mobile@v0.0.0-20240604190613-2782386b8afd/bind/java/context_android.go:9:10: fatal error: jni.h: No such file or directory
    9 | //#include <jni.h>
      |          ^~~~~~~
compilation terminated.]

make: *** [Makefile:2: all] Error 1
```

**Comment by vikulin** [comment]
> > could you please give exact golang, gomobile versions where you have solved this issue for?
> 
> Works with latest.
> 
> You can see [this Action](https://github.com/celzero/firestack/blob/b9e9dcd6796afe4ff036f254d671531f4ae8ac0d/.github/workflows/go.yml) ([recent run](https://github.com/celzero/firestack/actions/runs/9531658646/job/26272825170)) which builds AAR (Android Archive) with go1.22 just fine ([gomobile install/init in Makefile](https://github.com/celzero/firestack/blob/b9e9dcd6796afe4ff036f254d671531f4ae8ac0d/Makefile#L53) via [make-aar](https://github.com/celzero/firestack/blob/b9e9dcd6796afe4ff036f254d671531f4ae8ac0d/make-aar#L64)).

Can you please confirm the build works locally from command line **without** GitHub Actions run?

**Comment by yiitz** [comment]
golang.org/x/mobile v0.0.0-20240320162201-c76e57eead38
go version go1.22.2 darwin/amd64
I build with the above version locally a few days ago, and it works well.

**Comment by vikulin** [comment]
> > > > could you please give exact golang, gomobile versions where you have solved this issue for?
> > > 
> > > 
> > > Works with latest.
> > > You can see [this Action](https://github.com/celzero/firestack/blob/b9e9dcd6796afe4ff036f254d671531f4ae8ac0d/.github/workflows/go.yml) ([recent run](https://github.com/celzero/firestack/actions/runs/9531658646/job/26272825170)) which builds AAR (Android Archive) with go1.22 just fine ([gomobile install/init in Makefile](https://github.com/celzero/firestack/blob/b9e9dcd6796afe4ff036f254d671531f4ae8ac0d/Makefile#L53) via [make-aar](https://github.com/celzero/firestack/blob/b9e9dcd6796afe4ff036f254d671531f4ae8ac0d/make-aar#L64)).
> > 
> > 
> > Can you please confirm the build works locally from command line **without** GitHub Actions run?
> 
> golang.org/x/mobile v0.0.0-20240320162201-c76e57eead38 go version go1.22.2 darwin/amd64 I build with the above version locally a few days ago, and it works well.

Originally, the issue is reported for ```linux/amd64``` not for ```MacOS```.

**Comment by vikulin** [comment]
Installed golang 1.22.4 on clean Ubuntu 24.04, issue is not reproducing.
