### ISSUE TITLE
go 1.21.5 breaks golangci-lint, works with go 1.21.4

### ISSUE THREAD

**Issue by nicks** [golang/go#64592]
### Go version

go version go1.21.5 linux/amd64

### What operating system and processor architecture are you using (`go env`)?

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/nick/.cache/go-build'
GOENV='/home/nick/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/nick/.gvm/pkgsets/go1.21.5/global/pkg/mod'
GONOPROXY='github.com/docker'
GONOSUMDB='github.com/docker'
GOOS='linux'
GOPATH='/home/nick/.gvm/pkgsets/go1.21.5/global'
GOPRIVATE='github.com/docker'
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/home/nick/.gvm/gos/go1.21.5'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/home/nick/.gvm/gos/go1.21.5/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.21.5'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/home/nick/src/scratch/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build267141797=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

Repro steps:
1. Download golangci-lint v1.52.2 (https://github.com/golangci/golangci-lint/releases/tag/v1.52.2)
2. Install go v1.21.5
3. Use the following main.go

```
package main

import (
	"github.com/segmentio/analytics-go/v3"
)

func main() {
	var x analytics.Client
	_ = x
}
```

4. `~/Downloads/golangci-lint-1.52.2-linux-amd64/golangci-lint run .`

### What did you expect to see?

golangci-lint to pass

### What did you see instead?

golangci-lint fails with this error:

```
~/Downloads/golangci-lint-1.52.2-linux-amd64/golangci-lint run .
main.go:1: : # github.com/nicks/scratch
./main.go:8:6: invalid composite literal type analytics.Client (typecheck)
package main
../../../linuxbrew/.linuxbrew/Cellar/go/1.21.5/libexec/src/net/http/internal/chunked.go:79:14: undefined: max (typecheck)
	cr.excess = max(cr.excess, 0)
```

Looks like this was broken by https://github.com/golang/go/commit/285ef16b3872faccb877abaef5e481a630acdaf2, which added the new `max` syntax

Rolling back to go 1.21.4 fixes the problem.

**Comment by mauri870** [comment]
This seems to be a golanci-lint issue.

See https://github.com/golangci/golangci-lint/issues/3718

**Comment by kvmw** [comment]
Having the exact same issue after upgrading to 1.21.5.  rolling back to 1.21.4 or earlier version fixes the problem.
