### ISSUE TITLE
cmd/go: TestScript/cover_pkgall_multiple_mains broken at head

### ISSUE THREAD

**Issue by bcmills** [golang/go#31963]
It's not clear to me when it regressed; it was masked in the dashboard by #31263. 😞

I'll try bisecting.

```
--- FAIL: TestScript (0.00s)
    --- FAIL: TestScript/cover_pkgall_multiple_mains (14.06s)
        script_test.go:192: 
            # This test checks that multiple main packages can be tested
            # with -coverpkg=all without duplicate symbol errors.
            # Verifies golang.org/issue/30374. (14.057s)
            > env GO111MODULE=on
            > [short] skip
            > go test -coverpkg=all ./...
            [stdout]
            ?   	example.com/cov/mainonly	[no test files]
            FAIL	example.com/cov/mainwithtest [build failed]
            FAIL	example.com/cov/xtest [build failed]
            [stderr]
            # example.com/cov/xtest.test
            2019/05/10 14:46:08 duplicate symbol main.main (types 1 and 1) in main and $WORK/b059/_pkg_.a(_go_.o)
            # example.com/cov/mainwithtest.test
            2019/05/10 14:46:08 duplicate symbol main.main (types 1 and 1) in main and $WORK/b054/_pkg_.a(_go_.o)
            [exit status 2]
            FAIL: testdata/script/cover_pkgall_multiple_mains.txt:9: unexpected command failure
            
FAIL
```

CC @jayconrod

**Comment by bcmills** [comment]
`git bisect` points to [CL 174657](https://golang.org/cl/174657) (CC @cherrymui @aclements).

**Comment by bcmills** [comment]
Duplicate of #31946
