### ISSUE TITLE
x/mobile/cmd/gobind: TestGobind/.*/Go-Cgopkg broken at CL 437298

### ISSUE THREAD

**Issue by bcmills** [golang/go#56292]
https://build.golang.org/log/c656c3d100391699f5e7a0389263d3a2be0a6497:
```
--- FAIL: TestGobind (10.23s)
    --- FAIL: TestGobind/GOPATH (5.18s)
        --- FAIL: TestGobind/GOPATH/Go-Cgopkg (1.59s)
            gobind_test.go:132: GO111MODULE=off gobind -lang go,java,objc golang.org/x/mobile/bind/testdata/cgopkg failed: exit status 1: // Code generated by gobind. DO NOT EDIT.
…
    --- FAIL: TestGobind/Modules (5.05s)
        --- FAIL: TestGobind/Modules/Go-Cgopkg (1.58s)
            gobind_test.go:132: GO111MODULE=on gobind -lang go,java,objc golang.org/x/mobile/bind/testdata/cgopkg failed: exit status 1: // Code generated by gobind. DO NOT EDIT.
…
FAIL
FAIL	golang.org/x/mobile/cmd/gobind	11.353s
```

The first failure on the dashboard was at https://go.dev/cl/437298, although the `x` repos don't always test every Go commit.

Unfortunately, since these tests don't produce [useful failure messages](https://go.dev/wiki/CodeReviewComments#useful-test-failures), it's hard for me to tell why they're even failing.

(attn @hyangah per https://dev.golang.org/owners; CC @hajimehoshi @golang/android @golang/ios)

**Comment by bcmills** [comment]
(I do see an `exit status 1` in the failure message, but I don't see anything in the output of the command that would explain why it exited with nonzero status.)

**Comment by hajimehoshi** [comment]
My previous change might cause this issue. I'll take a look

**Comment by bcmills** [comment]
I cleaned up the test output in https://go.dev/cl/443655, and got the error output down to something more comprehensible:

```
~/x/mobile$ go1.19.2 test ./cmd/gobind -run=TestGobind/Modules/Go-Cgopkg
ok      golang.org/x/mobile/cmd/gobind  1.621s

~/x/mobile$ gotip test ./cmd/gobind -run=TestGobind/Modules/Go-Cgopkg
--- FAIL: TestGobind (1.61s)
    --- FAIL: TestGobind/Modules (1.61s)
        --- FAIL: TestGobind/Modules/Go-Cgopkg (1.54s)
            gobind_test.go:115: stderr (/tmp/go-build4070383437/b001/gobind.test -lang go,java,objc golang.org/x/mobile/bind/testdata/cgopkg):
                unable to import bind/java: [-: go build golang.org/x/mobile/bind/java: # golang.org/x/mobile/bind/java
                bind/java/context_android.go:9:10: fatal error: jni.h: No such file or directory
                    9 | //#include <jni.h>
                      |          ^~~~~~~
                compilation terminated.]
            gobind_test.go:143: /tmp/go-build4070383437/b001/gobind.test -lang go,java,objc golang.org/x/mobile/bind/testdata/cgopkg: exit status 1
FAIL
FAIL    golang.org/x/mobile/cmd/gobind  1.642s
```

**Comment by bcmills** [comment]
`git bisect` on my workstation confirms that this test started failing at CL 437298 exactly:
```
01604129aee8bfc9dd3e2fffd2ad8f772a3089ec is the first bad commit
commit 01604129aee8bfc9dd3e2fffd2ad8f772a3089ec
Author: Michael Matloob <matloob@golang.org>
Date:   Fri Sep 30 16:49:42 2022 -0400

    cmd/go: do not exit with non-zero code from go list -e -export

    go list -e -export puts errors running build actions on the load.Package
    corresponding to the failed action rather than exiting with a non zero
    exit code.

    For #25842

    Change-Id: I1fea85cc5a0557f514fe9d4ed3b6a858376fdcde
    Reviewed-on: https://go-review.googlesource.com/c/go/+/437298
    Run-TryBot: Bryan Mills <bcmills@google.com>
    Reviewed-by: Bryan Mills <bcmills@google.com>
    TryBot-Result: Gopher Robot <gobot@golang.org>
    Auto-Submit: Bryan Mills <bcmills@google.com>
    Reviewed-by: Michael Matloob <matloob@golang.org>

 src/cmd/go/internal/list/list.go             |  3 +
 src/cmd/go/internal/work/action.go           |  1 +
 src/cmd/go/internal/work/exec.go             | 95 +++++++++++++++++-----------
 src/cmd/go/internal/work/gc.go               |  4 +-
 src/cmd/go/testdata/script/list_export_e.txt | 19 ++++++
 5 files changed, 84 insertions(+), 38 deletions(-)
 create mode 100644 src/cmd/go/testdata/script/list_export_e.txt
```

**Comment by hyangah** [comment]
@hajimehoshi This is reproducible only with the go built on tip in the path (after cl/437298)

```
$ go install golang.org/dl/gotip@latest
$ gotip download
$ gotip install golang.org/x/mobile/cmd/gobind@latest
$ export PATH=$(gotip env GOROOT)/bin:$PATH
$ GOOS=android CGO_ENABLED=1 gobind -lang=go,java golang.org/x/mobile/bind/testdata/cgopkg
```

With cl/437298 (that is a bug fix IMO), the error is reported in the Error field and eventually in go/packages.Package's Errors. 
```
$ CGO_ENABLED=1 GOOS=android gotip list -e -json=Name,ImportPath,Error -compiled=true -test=false -export=false -deps=false -find=true golang.org/x/mobile/bind/java
{
        "ImportPath": "golang.org/x/mobile/bind/java",
        "Name": "java",
        "Error": {
                "ImportStack": null,
                "Pos": "",
                "Err": "go build golang.org/x/mobile/bind/java: # golang.org/x/mobile/bind/java\n../../bind/java/context_android.go:9:10: fatal error: 'jni.h' file not found\n#include \u003cjni.h\u003e\n         ^~~~~~~\n1 error generated.\n"
        }
}
```

As a result, the `gobind` command checks the Errors field and fails.
https://github.com/golang/mobile/blob/51f526d719ab0aa30e2c27a3c1701819189ae1de/cmd/gobind/gen.go#L384

Before cl/437298, `go list -e` failed with an error (`*exec.ExitError`)
```
$ CGO_ENABLED=1 GOOS=android go1.19.1 list -e -json=Name,ImportPath,Error -compiled=true -test=false -export=false -deps=false -find=true golang.org/x/mobile/bind/java
# golang.org/x/mobile/bind/java
../../bind/java/context_android.go:9:10: fatal error: 'jni.h' file not found
#include <jni.h>
         ^~~~~~~
1 error generated.
{
        "ImportPath": "golang.org/x/mobile/bind/java",
        "Name": "java"
}
```

This failure error is reported as a `friendlyErr` of `gocmdRunner.RunRaw` call in https://github.com/golang/tools/blob/bc2e3aeaba30b86fc421aefdfc78094b43700314/go/packages/golist.go#L950.
 
But it looks like `go/packages` dropped this error on the floor... Interestingly, [the comment here](https://github.com/golang/tools/blob/master/go/packages/golist.go#L974-L975) says:

> 		// Is there an error running the C compiler in cgo? This will be reported in the "Error" field
>		// and should be suppressed by go list -e.

There are some heuristic scanning of `stderr` but this failure mode is not captured. As a result, package load succeeds and the returned Package carries no error.

The previous bug depended on the bug in `go list`. It's unclear to me whether gobind has to handle this error.
It looks to me that gobind attempts to load the package just to find out the package directory. Then, we don't `NeedCompiledGoFiles` bit.

**Comment by hyangah** [comment]
Verified long builder passed with this commit.
