### ISSUE TITLE
x/mobile/app: Build error on darwin_amd64

### ISSUE THREAD

**Issue by shazow** [golang/go#11827]
Recent patch that adds keyboard events to x/mobile on OSX (https://github.com/golang/mobile/commit/de4ba64cf58948d044322d0a9743ef5cc46ef5c7, cc @crawshaw) is failing to build on 10.9.5. Looks like it's because the `ARepeat` property is only available on OSX 10.10 and newer: https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSEvent_Class/#//apple_ref/occ/instp/NSEvent/ARepeat

```
$ go build .
# golang.org/x/mobile/app
../../local/go1.5/src/golang.org/x/mobile/app/darwin_amd64.m:192:15: error: property 'ARepeat' not found on object of type 'NSEvent *'
```

`go version devel +71832ff Fri Jul 3 21:39:04 2015 +0000 darwin/amd64` on OSX 10.9.5
