### ISSUE TITLE
cmd/compile: all.bash test cases fail when new export format is enabled

### ISSUE THREAD

**Issue by griesemer** [golang/go#13977]
The change https://go-review.googlesource.com/14204 (revision 67faca7d9c54b367aee5fdeef2d5dd609fcf99d0) from 2/11/2015 broke a few tests in all.bash when running with the binary export format enabled (which is disabled by default). Found using git bisect.

Specifically, it appears that tests that use relative import paths (as in test/fixedbugs/bug437.dir) fail:

$ cd $GOROOT/test/fixedbugs/bug437.dir
$ go tool compile -newexport one.go && go tool compile -newexport two.go && go tool compile x.go && go tool link x.o

leads to:

type./Users/gri/go/test/fixedbugs/bug437.dir/two.S2: go.importpath./Users/gri/go/test/fixedbugs/bug437.dir/two.: not defined
type./Users/gri/go/test/fixedbugs/bug437.dir/two.S2: undefined: go.importpath./Users/gri/go/test/fixedbugs/bug437.dir/two.

Removing the following change:

https://go-review.googlesource.com/#/c/14204/54/src/cmd/compile/internal/gc/go.y

and rebuild the compiler only and then run above test, it works.

However, removing the change won't build the system from scratch.

@michaelmatloob pointed me at https://go-review.googlesource.com/#/c/14204/49..51/src/cmd/compile/internal/gc/go.y which gives some context about the offending change.
