### ISSUE TITLE
x/net: undefined: tls.Dialer note: module requires Go 1.17

### ISSUE THREAD

**Issue by srPuebla** [golang/go#45943]
### What version of Go are you using (`go version`)?

golang:1.14.3-alpine3.11

<pre>
$ go version
1.14.3
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

golang:1.14.3-alpine3.11

</pre></details>

### What did you do?

docker-compose build

### What did you expect to see?

go: downloading golang.org/x/net v0.0.0-20200602114024-627f9648deb9

### What did you see instead?

golang.org/x/net/http2
/go/pkg/mod/golang.org/x/net@v0.0.0-20210504132125-bbd867fde50d/http2/transport.go:598:14: undefined: tls.Dialer
note: module requires Go 1.17

**Comment by ianlancetaylor** [comment]
Dup of #45942.  You need to update to Go 1.15 or later.

**Comment by ianlancetaylor** [comment]
Since this came up five times in 24 hours, I went ahead and patches golang.org/x/net so that it will work with versions of Go before 1.15.  That should fix this problem.  I still strongly encourage everyone to upgrade to a supported version of Go, and I do not promise that this will not break again in the future.
