### ISSUE TITLE
x/build: LUCI swarming bot works with Python 3.13 but not Python 3.14 due to reliance on removed pkgutil.get_loader

### ISSUE THREAD

**Issue by n2vi** [golang/go#80220]
### Go version

I use go1.27rc1 there, but this is probably not about Go. Python reports 3.14.4.

### Output of `go env` in your module/workspace:

```shell
not relevant?
```

### What did you do?

I tried to start the builder as usual.

### What did you see happen?

`2026/06/28 18:16:31 Downloading the swarming bot
2026/06/28 18:16:33 Starting the swarming bot /home/swarming/.swarming/swarming_bot.zip
Traceback (most recent call last):
  File "", line 198, in _run_module_as_main
  File "", line 88, in _run_code
  File "/home/swarming/.swarming/swarming_bot.zip/__main__.py", line 31, in 
    THIS_FILE = os.path.abspath(zip_package.get_main_script_path())
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/swarming/.swarming/swarming_bot.zip/utils/zip_package.py", line 238, in get_main_script_path
    path = get_module_zip_archive(main)
  File "/home/swarming/.swarming/swarming_bot.zip/utils/zip_package.py", line 217, in get_module_zip_archive
    loader = pkgutil.get_loader(module)
             ^^^^^^^^^^^^^^^^^^
AttributeError: module 'pkgutil' has no attribute 'get_loader'
2026/06/28 18:16:33 command execution /usr/local/bin/python3 /home/swarming/.swarming/swarming_bot.zip start_bot: exit status 1`

### What did you expect to see?

`pkgutil.get_loader` was deprecated a while ago and apparently was removed in Python 3.14. Has LUCI already been updated but my builder machine is not getting the update, or is this an update needed in LUCI?

**Comment by n2vi** [comment]
@golang/release

**Comment by dmitshur** [comment]
As far as I can tell, the swarming bot code hasn't been updated to be compatible with Python 3.14 yet, and you're among the first to notice and report this. I see that `pkgutil.get_loader` call is still there on line 217 in the latest version of [luci/client/utils/zip_package.py](https://source.chromium.org/chromium/infra/infra_superproject/+/main:infra/luci/client/utils/zip_package.py;l=217;drc=d3f990db2d0af033542c89d8bc1fc6a5cedf773d) as of this posting. So this isn't due to the update mechanism not working.

From looking at the logs of a typical `linux-amd64` builder, the python version being fetched there seems to be 3.11.9, way before `pkgutil.get_loader` was removed. There's a dimension for the python version, which makes it convenient to see what other LUCI bots are using: not a single bot running Python 3.14 (https://chromium-swarm.appspot.com/botlist?f=python%3A3.14), some running 3.13 (https://chromium-swarm.appspot.com/botlist?f=python%3A3.13), and many running older versions of Python 3.

The next steps here would be to file a bug in the LUCI issue tracker at https://issues.chromium.org/issues?q=status:open%20componentid:1456370, or perhaps rely on the existing https://issues.chromium.org/issues/40618684 tracking bug. Until the swarming bot is updated to support Python 3.14+, a workaround is to stay with 3.13.

**Comment by n2vi** [comment]
Filed https://issues.chromium.org/issues/536346612.

**Comment by n2vi** [comment]
I've  heard no direct response from Chrome folks, but stumbled across
https://issues.chromium.org/issues/537680330#comment41
which makes clear they don't intend us to use the system Python.

So, I would suggest that someone edit go.dev/wiki/DashboardBuilders
to change the Builder Requirements from "Python 3 installed" to exactly
which pinned version of python you want from depot_tools and how
outsiders can get it.

**Comment by dmitshur** [comment]
It's not very visible on the issue, but as of today it does have a pending code change (https://crrev.com/c/8265616).

**Comment by n2vi** [comment]
Thanks! I don't think I have access to that url but sounds promising; I'm happy to wait for the new code.

In the meantime, I can at least confirm that go1.27.0 builds cleanly on ppc64 openbsd 8.0-beta, so I don't anticipate any crisis once LUCI finally starts working again.

**Comment by dmitshur** [comment]
Closing this since https://issues.chromium.org/issues/536346612 is resolved now. Please feel free to try it again with Python 3.14.

**Comment by n2vi** [comment]
Confirmed working fine now. Thanks!
