### ISSUE TITLE
import/path: issue title go:linkname giving error "invalid reference to syscall.munmap" in go 1.23.0

### ISSUE THREAD

**Issue by ddbera95** [golang/go#68985]
### Go version

go version go1.23.0 linux/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE='on'
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/dhaval/.cache/go-build'
GOENV='/home/dhaval/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/dhaval/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/dhaval/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/snap/go/10698'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/snap/go/10698/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.23.0'
GODEBUG=''
GOTELEMETRY='local'
GOTELEMETRYDIR='/home/dhaval/.config/go/telemetry'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/home/dhaval/GolandProjects/demo/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build1058670265=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

I am using github.com/ii64/gouring library, i was using go 1.22 and it was working fine but after updating go version 1.22 to 1.23.0 it is giving compilation error.

### What did you see happen?

After updating to 1.23.0 i am getting error "invalid reference to syscall.munmap"

when i see inside library there were go:linkname used for syscall.munmap
```go
//go:linkname munmap syscall.munmap
func munmap(addr unsafe.Pointer, length uintptr) (err error)
``` 

### What did you expect to see?

I was not expecting compilation error

@rsc please help in the same

**Comment by seankhliao** [comment]
see https://go.dev/doc/go1.23#linker
