### ISSUE TITLE
x/net: undefined: tls.Dialer note: module requires Go 1.17

### ISSUE THREAD

**Issue by artemidas** [golang/go#45942]
### What version of Go are you using (`go version`)?

I'm using golang docker image on CircleCI [golang:1.14-alpine3.12](https://hub.docker.com/_/golang/?tab=tags&page=1&ordering=last_updated&name=1.14-alpine3.12)

### Does this issue reproduce with the latest release?
Yes, like 1 hour after the last changes were pushed.

### What did you do?
<pre>
$ go vet -structtag=false -unmarshal -assign -atomic -unsafeptr -unusedresult ./...
</pre>
Getting error:
<pre>
# golang.org/x/net/http2
/go/pkg/mod/golang.org/x/net@v0.0.0-20210504132125-bbd867fde50d/http2/transport.go:598:14: undefined: tls.Dialer
note: module requires Go 1.17

Exited with code exit status 2
</pre>

### What did you expect to see?
<pre>
CircleCI received exit code 0
</pre>

### What did you see instead?
<pre>
CircleCI received exit code 2
</pre>

**Comment by ianlancetaylor** [comment]
Our policy with repos like golang.org/x/net is that they only  have to support the last two Go releases.  Today that is the 1.15 and 1.16 releases.  You are using 1.14.  tls.Dialer was added in 1.15.  In order to build tip x/net, you will need to update your Go installation.

**Comment by ianlancetaylor** [comment]
Since this came up five times in 24 hours, I went ahead and patches golang.org/x/net so that it will work with versions of Go before 1.15.  That should fix this problem.  I still strongly encourage everyone to upgrade to a supported version of Go, and I do not promise that this will not break again in the future.

**Comment by wang51089** [comment]
it is not an easy job for me to push the company`s k8s team to update go installation. So which version of golang.org/x/net is compatible with go 1.15 please

**Comment by ianlancetaylor** [comment]
@wang51089 You'll probably get a better answer on a forum.  See https://go.dev/wiki/Questions.  As far as I know git revision 0714010a04edd230e18075cd951dd826f04b1e11 works with 1.15.  But note that 1.15 is no longer supported.

**Comment by vediyappan-villali** [comment]
I am also getting the similar error. Even I am using go version 1.17. Is this issue fixed?

# golang.org/x/net/http2
../../../../pkg/mod/golang.org/x/net@v0.0.0-20211112202133-69e39bad7dc2/http2/transport.go:417:45: undefined: os.ErrDeadlineExceeded
note: module requires Go 1.17

vediyappan@LX-9N9H9R2:~/work/yoctoproject/build$ go version
go version go1.17.8 linux/amd64
