### ISSUE TITLE
gollvm: can't build using Clang 11.0RC2 (Linux x86_64).  go.cc: no member named 'need_eqtype' in 'go_create_gogo_args'; go-llvm-typemanager.cpp: no matching function for call to 'get'

### ISSUE THREAD

**Issue by advancedwebdeveloper** [golang/go#41132]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.15
</pre>

### Does this issue reproduce with the latest release?
I think so.

### What operating system and processor architecture are you using (`go env`)?

Ubuntu 20 x86_64

### What did you do?

Just an ordinary compilation of gollvm project, using [LLVM 11.0.0-rc2](https://github.com/llvm/llvm-project/releases/tag/llvmorg-11.0.0-rc2)
Passed [libc++](https://libcxx.llvm.org/docs/UsingLibcxx.html#using-libc-on-linux) into C++ compiler flags:
-DCMAKE_CXX_FLAGS=-stdlib=libc++
.
And limited myself to -DLLVM_TARGETS_TO_BUILD=X86 .

### What did you expect to see?
Normal build process, using Ninja.

### What did you see instead?

[1/1411] Building CXX object tools/gollvm/bridge/CMakeFiles/LLVMCppGoFrontEnd.dir/__/gofrontend/go/go.cc.o
FAILED: tools/gollvm/bridge/CMakeFiles/LLVMCppGoFrontEnd.dir/__/gofrontend/go/go.cc.o 
/usr/bin/clang++ -DGTEST_HAS_RTTI=0 -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Itools/gollvm/bridge -I/media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/tools/gollvm/bridge -Iinclude -I/media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/include -Itools/gollvm/external/install/include -I/media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/tools/gollvm/gofrontend/go -stdlib=libc++ -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -fdiagnostics-color -ffunction-sections -fdata-sections -Os -DNDEBUG  -fno-exceptions -fno-rtti -std=c++14 -MD -MT tools/gollvm/bridge/CMakeFiles/LLVMCppGoFrontEnd.dir/__/gofrontend/go/go.cc.o -MF tools/gollvm/bridge/CMakeFiles/LLVMCppGoFrontEnd.dir/__/gofrontend/go/go.cc.o.d -o tools/gollvm/bridge/CMakeFiles/LLVMCppGoFrontEnd.dir/__/gofrontend/go/go.cc.o -c /media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/tools/gollvm/gofrontend/go/go.cc
In file included from /media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/tools/gollvm/gofrontend/go/go.cc:15:
/media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/tools/gollvm/gofrontend/go/gogo.h:3625:3: warning: 'type' overrides a member function but is not marked 'override' [-Wsuggest-override]
  type(Type*);
  ^
/media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/tools/gollvm/gofrontend/go/gogo.h:3587:3: note: overridden virtual function is here
  type(Type*);
  ^
/media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm
**/llvm-project/llvm/tools/gollvm/gofrontend/go/go.cc:49:13:
 error: no member named 'need_eqtype' in 'go_create_gogo_args'**
  if (args->need_eqtype)
      ~~~~  ^
**/media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm
/llvm-project/llvm/tools/gollvm/gofrontend/go/go.cc:50:35:
 error: no member named 'need_eqtype' in 'go_create_gogo_args'**
    ::gogo->set_need_eqtype(args->need_eqtype);
                            ~~~~  ^
1 warning and 2 errors generated.

**Comment by advancedwebdeveloper** [comment]
[5/1391] /usr/bin/clang++ -DGTEST_HAS_RTTI=0 -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Itools/gollvm/bridge -I/media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/tools/gollvm/bridge -Iinclude -I/media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/include -Itools/gollvm/external/install/include -I/media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/tools/gollvm/gofrontend/go -stdlib=libc++ -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -fdiagnostics-color -ffunction-sections -fdata-sections -Os -DNDEBUG  -fno-exceptions -fno-rtti -std=c++14 -MD -MT tools/gollvm/bridge/CMakeFiles/LLVMCppGoFrontEnd.dir/go-llvm-typemanager.cpp.o -MF tools/gollvm/bridge/CMakeFiles/LLVMCppGoFrontEnd.dir/go-llvm-typemanager.cpp.o.d -o tools/gollvm/bridge/CMakeFiles/LLVMCppGoFrontEnd.dir/go-llvm-typemanager.cpp.o -c /media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/tools/gollvm/bridge/go-llvm-typemanager.cpp
FAILED: tools/gollvm/bridge/CMakeFiles/LLVMCppGoFrontEnd.dir/go-llvm-typemanager.cpp.o 
/usr/bin/clang++ -DGTEST_HAS_RTTI=0 -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Itools/gollvm/bridge -I/media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/tools/gollvm/bridge -Iinclude -I/media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/include -Itools/gollvm/external/install/include -I/media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/tools/gollvm/gofrontend/go -stdlib=libc++ -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -fdiagnostics-color -ffunction-sections -fdata-sections -Os -DNDEBUG  -fno-exceptions -fno-rtti -std=c++14 -MD -MT tools/gollvm/bridge/CMakeFiles/LLVMCppGoFrontEnd.dir/go-llvm-typemanager.cpp.o -MF tools/gollvm/bridge/CMakeFiles/LLVMCppGoFrontEnd.dir/go-llvm-typemanager.cpp.o.d -o tools/gollvm/bridge/CMakeFiles/LLVMCppGoFrontEnd.dir/go-llvm-typemanager.cpp.o -c /media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/tools/gollvm/bridge/go-llvm-typemanager.cpp
In file included from /media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/tools/gollvm/bridge/go-llvm-typemanager.cpp:15:
In file included from /media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/tools/gollvm/bridge/go-llvm-bexpression.h:17:
/media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/tools/gollvm/bridge/go-llvm-linemap.h:35:3: warning: 'start_file' overrides a member function but is not marked 'override' [-Wsuggest-override]
  start_file(const char* file_name, unsigned int line_begin);
  ^
/media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/tools/gollvm/gofrontend/go/go-linemap.h:42:3: note: overridden virtual function is here
  start_file(const char* file_name, unsigned int line_begin) = 0;
  ^
In file included from /media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/tools/gollvm/bridge/go-llvm-typemanager.cpp:15:
In file included from /media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/tools/gollvm/bridge/go-llvm-bexpression.h:17:
/media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/tools/gollvm/bridge/go-llvm-linemap.h:38:3: warning: 'start_line' overrides a member function but is not marked 'override' [-Wsuggest-override]
  start_line(unsigned int line_number, unsigned int line_size);
  ^
/media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/tools/gollvm/gofrontend/go/go-linemap.h:48:3: note: overridden virtual function is here
  start_line(unsigned int line_number, unsigned int line_size) = 0;
  ^
In file included from /media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/tools/gollvm/bridge/go-llvm-typemanager.cpp:15:
In file included from /media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/tools/gollvm/bridge/go-llvm-bexpression.h:17:
/media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/tools/gollvm/bridge/go-llvm-linemap.h:41:3: warning: 'get_location' overrides a member function but is not marked 'override' [-Wsuggest-override]
  get_location(unsigned int column);
  ^
/media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/tools/gollvm/gofrontend/go/go-linemap.h:53:3: note: overridden virtual function is here
  get_location(unsigned int column) = 0;
  ^
In file included from /media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/tools/gollvm/bridge/go-llvm-typemanager.cpp:15:
In file included from /media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/tools/gollvm/bridge/go-llvm-bexpression.h:17:
/media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/tools/gollvm/bridge/go-llvm-linemap.h:44:3: warning: 'stop' overrides a member function but is not marked 'override' [-Wsuggest-override]
  stop();
  ^
/media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/tools/gollvm/gofrontend/go/go-linemap.h:58:3: note: overridden virtual function is here
  stop() = 0;
  ^
In file included from /media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/tools/gollvm/bridge/go-llvm-typemanager.cpp:15:
In file included from /media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/tools/gollvm/bridge/go-llvm-bexpression.h:17:
/media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/tools/gollvm/bridge/go-llvm-linemap.h:47:3: warning: 'to_string' overrides a member function but is not marked 'override' [-Wsuggest-override]
  to_string(Location);
  ^
/media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/tools/gollvm/gofrontend/go/go-linemap.h:64:3: note: overridden virtual function is here
  to_string(Location) = 0;
  ^
In file included from /media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/tools/gollvm/bridge/go-llvm-typemanager.cpp:15:
In file included from /media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/tools/gollvm/bridge/go-llvm-bexpression.h:17:
/media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/tools/gollvm/bridge/go-llvm-linemap.h:52:3: warning: 'location_line' overrides a member function but is not marked 'override' [-Wsuggest-override]
  location_line(Location);
  ^
/media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/tools/gollvm/gofrontend/go/go-linemap.h:72:3: note: overridden virtual function is here
  location_line(Location) = 0;
  ^
In file included from /media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/tools/gollvm/bridge/go-llvm-typemanager.cpp:15:
In file included from /media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/tools/gollvm/bridge/go-llvm-bexpression.h:17:
/media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/tools/gollvm/bridge/go-llvm-linemap.h:55:3: warning: 'location_file' overrides a member function but is not marked 'override' [-Wsuggest-override]
  location_file(Location);
  ^
/media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/tools/gollvm/gofrontend/go/go-linemap.h:68:3: note: overridden virtual function is here
  location_file(Location) = 0;
  ^
In file included from /media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/tools/gollvm/bridge/go-llvm-typemanager.cpp:15:
In file included from /media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/tools/gollvm/bridge/go-llvm-bexpression.h:17:
/media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/tools/gollvm/bridge/go-llvm-linemap.h:66:3: warning: 'get_predeclared_location' overrides a member function but is not marked 'override' [-Wsuggest-override]
  get_predeclared_location();
  ^
/media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/tools/gollvm/gofrontend/go/go-linemap.h:80:3: note: overridden virtual function is here
  get_predeclared_location() = 0;
  ^
In file included from /media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/tools/gollvm/bridge/go-llvm-typemanager.cpp:15:
In file included from /media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/tools/gollvm/bridge/go-llvm-bexpression.h:17:
/media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/tools/gollvm/bridge/go-llvm-linemap.h:69:3: warning: 'get_unknown_location' overrides a member function but is not marked 'override' [-Wsuggest-override]
  get_unknown_location();
  ^
/media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/tools/gollvm/gofrontend/go/go-linemap.h:85:3: note: overridden virtual function is here
  get_unknown_location() = 0;
  ^
In file included from /media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/tools/gollvm/bridge/go-llvm-typemanager.cpp:15:
In file included from /media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/tools/gollvm/bridge/go-llvm-bexpression.h:17:
/media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/tools/gollvm/bridge/go-llvm-linemap.h:72:3: warning: 'is_predeclared' overrides a member function but is not marked 'override' [-Wsuggest-override]
  is_predeclared(Location);
  ^
/media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/tools/gollvm/gofrontend/go/go-linemap.h:90:3: note: overridden virtual function is here
  is_predeclared(Location) = 0;
  ^
In file included from /media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/tools/gollvm/bridge/go-llvm-typemanager.cpp:15:
In file included from /media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/tools/gollvm/bridge/go-llvm-bexpression.h:17:
/media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/tools/gollvm/bridge/go-llvm-linemap.h:75:3: warning: 'is_unknown' overrides a member function but is not marked 'override' [-Wsuggest-override]
  is_unknown(Location);
  ^
/media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/tools/gollvm/gofrontend/go/go-linemap.h:95:3: note: overridden virtual function is here
  is_unknown(Location) = 0;
  ^
In file included from /media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/tools/gollvm/bridge/go-llvm-typemanager.cpp:16:
/media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/tools/gollvm/bridge/go-llvm-cabi-oracle.h:229:17: warning: 'analyzeABIParam' overrides a member function but is not marked 'override' [-Wsuggest-override]
  CABIParamInfo analyzeABIParam(Btype *pType, ABIState &state);
                ^
/media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/tools/gollvm/bridge/go-llvm-cabi-oracle.h:217:25: note: overridden virtual function is here
  virtual CABIParamInfo analyzeABIParam(Btype *pType, ABIState &state) = 0;
                        ^
/media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/tools/gollvm/bridge/go-llvm-cabi-oracle.h:230:17: warning: 'analyzeABIReturn' overrides a member function but is not marked 'override' [-Wsuggest-override]
  CABIParamInfo analyzeABIReturn(Btype *resultType, ABIState &state);
                ^
/media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/tools/gollvm/bridge/go-llvm-cabi-oracle.h:216:25: note: overridden virtual function is here
  virtual CABIParamInfo analyzeABIReturn(Btype *resultType, ABIState &state) = 0;
                        ^
/media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/tools/gollvm/bridge/go-llvm-cabi-oracle.h:244:17: warning: 'analyzeABIParam' overrides a member function but is not marked 'override' [-Wsuggest-override]
  CABIParamInfo analyzeABIParam(Btype *pType, ABIState &state);
                ^
/media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/tools/gollvm/bridge/go-llvm-cabi-oracle.h:217:25: note: overridden virtual function is here
  virtual CABIParamInfo analyzeABIParam(Btype *pType, ABIState &state) = 0;
                        ^
/media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/tools/gollvm/bridge/go-llvm-cabi-oracle.h:245:17: warning: 'analyzeABIReturn' overrides a member function but is not marked 'override' [-Wsuggest-override]
  CABIParamInfo analyzeABIReturn(Btype *resultType, ABIState &state);
                ^
/media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/tools/gollvm/bridge/go-llvm-cabi-oracle.h:216:25: note: overridden virtual function is here
  virtual CABIParamInfo analyzeABIReturn(Btype *resultType, ABIState &state) = 0;
                        ^
/media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/tools/gollvm/bridge/go-llvm-typemanager.cpp:74:26: error: no matching function for call to 'get'
  llvmTwoFloatVecType_ = llvm::VectorType::get(llvmFloatType_, 2);
                         ^~~~~~~~~~~~~~~~~~~~~
/media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/include/llvm/IR/DerivedTypes.h:445:22: note: candidate function not viable: no known conversion from 'int' to 'llvm::ElementCount' for 2nd argument
  static VectorType *get(Type *ElementType, ElementCount EC);
                     ^
/media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/include/llvm/IR/DerivedTypes.h:453:22: note: candidate function not viable: no known conversion from 'int' to 'const llvm::VectorType *' for 2nd argument
  static VectorType *get(Type *ElementType, const VectorType *Other) {
                     ^
/media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/include/llvm/IR/DerivedTypes.h:447:22: note: candidate function not viable: requires 3 arguments, but 2 were provided
  static VectorType *get(Type *ElementType, unsigned NumElements,
                     ^
/media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/tools/gollvm/bridge/go-llvm-typemanager.cpp:585:15: warning: unused variable 'rtyp' [-Wunused-variable]
  llvm::Type *rtyp = rbtype->type();
              ^
/media/ubuntu/4d5fa4ce-dc9b-4cb0-934c-72533ffc1586/gollvm/llvm-project/llvm/tools/gollvm/bridge/go-llvm-typemanager.cpp:1803:5: warning: default label in switch which covers all enumeration values [-Wcovered-switch-default]
    default: assert(0);
    ^
17 warnings and 1 error generated.

**Comment by advancedwebdeveloper** [comment]
It seems to be that 

[llvmTwoFloatVecType_ = llvm::VectorType::get(llvmFloatType_, 2);](https://go.googlesource.com/gollvm/+/refs/heads/master/bridge/go-llvm-typemanager.cpp#74)

[if (args->need_eqtype)](https://go.googlesource.com/gofrontend/+/refs/heads/master/go/go.cc#49)

[::gogo->set_need_eqtype(args->need_eqtype);](https://go.googlesource.com/gofrontend/+/refs/heads/master/go/go.cc#50)

are referenced calls.
Maybe there are other bugs - but other targets unavailable, until these would be allowed to build.

Ivan

**Comment by ianlancetaylor** [comment]
CC @tham @cherrymui

**Comment by thanm** [comment]
Thanks. I'll send a patch.

**Comment by thanm** [comment]
This should be fixed now with CL's 251777 + 251778 (just submitted). Let me know if you see any other issues.
