### ISSUE TITLE
gccgo: vendoring doesn't work in gcc 6.1

### ISSUE THREAD

**Issue by urandom** [golang/go#15628]
Please answer these questions before submitting your issue. Thanks!
1. What version of Go are you using (`go version`)?
   go version go1.6.1 gccgo (GCC) 6.1.1 20160501 linux/amd64
2. What operating system and processor architecture are you using (`go env`)?
   GOARCH="amd64"
   GOBIN=""
   GOEXE=""
   GOHOSTARCH="amd64"
   GOHOSTOS="linux"
   GOOS="linux"
   GOPATH="/home/urandom/.go"
   GORACE=""
   GOROOT="/usr"
   GOTOOLDIR="/usr/lib/gcc/x86_64-pc-linux-gnu/6.1.1"
   GO15VENDOREXPERIMENT="1"
   CC="/usr/bin/gcc"
   GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
   CXX="/usr/bin/g++"
   CGO_ENABLED="1"
3. What did you do?
   go get -u github.com/hashicorp/consul
4. What did you expect to see?
   No errors
5. What did you see instead?
   # github.com/hashicorp/consul/vendor/github.com/armon/go-metrics/datadog
   
   github.com/hashicorp/consul/vendor/github.com/armon/go-metrics/datadog/dogstatsd.go:7:38: error: import file ‘github.com/DataDog/datadog-go/statsd’ not found
   "github.com/DataDog/datadog-go/statsd"

And many more after that

**Comment by mwhudson** [comment]
FWIW, I *think* this might be quite easy to fix: when compiling package p from GOPATH component q, pass -I q/pkg_GOOS_GOARCH_gccgo/vendor/ to gccgo, if it exists. (Or maybe it needs to be more complicated than this, I don't really know how vendoring is implemented)

**Comment by a13xb** [comment]
@mwhudson It should be. We have the same issue and work around it by using a manual shell script that adds vendor directory to the include path set.

**Comment by laboger** [comment]
This continues to fail with the upgrade in gcc trunk to Go 1.7.

**Comment by a13xb** [comment]
For anyone interested, we have added a dodgy workaround by setting `$GCCGO` to the path of this wrapper script, and setting `$REALGCCO` to the actual compiler path.
```
#!/usr/bin/env python
import os, sys
gccgo = os.environ['REALGCCGO']
args = sys.argv[1:]
work = [a for a in args if a.startswith('/tmp/go-build')][0]
args += ['-I', work + '/my-project-import-path/vendor']
os.execlp(gccgo, gccgo, *args)
```
I haven't had the patience to make a more general solution, but this one works OK for a single project.

**Comment by tamird** [comment]
Continues to fail with the upgrade in gcc trunk to go1.8rc3 (https://github.com/gcc-mirror/gcc/commit/905e0442b522f7724858a20657aa2e5dd207a25e).

**Comment by laboger** [comment]
I have submitted this CL for gccgo (gofrontend) to fix this problem.  https://go-review.googlesource.com/c/39590/.  Once it is approved I will submit the corresponding change to golang so it will work the same when using the option -compiler gccgo.  It fixes the example posted above.
