### PR TITLE
cmd/go: ignore UTF8 BOM when reading source code

### LINKED ISSUE #35726: cmd/go: imports fail to resolve in module mode when file contains a leading BOM
### What version of Go are you using (`go version`)?
<pre>
$ go version
go version go1.13.4 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\andyTsing\AppData\Local\go-build
set GOENV=C:\Users\andyTsing\AppData\Roaming\go\env  
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\andyTsing\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=D:\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\Temp\TXSSPrinter\BEService\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\ANDYTS~1\AppData\Local\Temp\go-build458686182=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
D:\Temp\TXSSPrinter\BEService>go run .
D:\Temp\TXSSPrinter\BEService>go build

https://github.com/andyTsing/BEService
This is a single-module, multi-package project that worked fine in the early 1.12 release and has had problems since the upgrade to 1.3.
Also, packages that also belong to different subdirectories, some of which have normal imports and some of which have abnormal imports, when I comment out the API section, are
The normal

### What did you expect to see?
A successful retrieval of a dependency.

### What did you see instead?
D:\Temp\TXSSPrinter\BEService>go run .
build github.com/andyTsing/BEService: cannot find module for path github.com/andyTsing/BEService/api

D:\Temp\TXSSPrinter\BEService>go build
build github.com/andyTsing/BEService: cannot find module for path github.com/andyTsing/BEService/api

### LINKED ISSUE #46198: cmd/go: embed directive doesn't work in file with leading bom
### What version of Go are you using (`go version`)?

<pre>
Golang version with bug:
go version go1.16.4 windows/amd64
go version go1.16.3 windows/amd64
go version go1.16.3 linux/amd64

</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
win，linux
</pre></details>

### What did you do?

embed file in win，linux

### What did you expect to see?
abcd1111

### What did you see instead?

invalid go:embed: build system did not supply embed configuration

----------

go source file allows utf8 with bom, all my go source code is in this format. It works well until it hits go://embed!

This problem has bothered me for a month. I was discussing it in the Golang Technology Park in China, 
and @del-xiong discovered the problem. Thanks him! ! !

# Golang version with bug:
go version go1.16.4 windows/amd64
go version go1.16.3 windows/amd64
go version go1.16.3 linux/amd64

# golang source code:

```
package main

import (
	_ "embed"
	"fmt"
)

//go:embed h1.txt
var sss string

func main() {
	fmt.Println(sss)
}
```

# error message:
xxx.go:8:3: invalid go:embed: build system did not supply embed configuration

## **how to let problem gone**
Currently,
change xxx.go source file format,from utf8withbom ,to utf8nobom,
line end is CRLF no need change.

# h1.txt content:
abcd1111

### LINKED ISSUE #46290: UTF8-BOM compile error with go mod
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.15 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
not sure

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/data/gopath/bin"
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/.golang/path"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/root/.golang/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/root/.golang/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/root/test/testbom/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build844510091=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

when I use Go module with utf-bom source code,  I cannot find the import package
```bash
$tree
.
├── go.mod
├── main.go   // UTF8-BOM
└── mypkg
    └── mypkg.go
```

```go
// main.go
package main

import (
	"fmt"
	"testbom/mypkg"
)

func SayHi() {
	fmt.Println("hi")
}

func main() {
	SayHi()
	mypkg.SayHello()
}
```

```go
//  mypkg.go
package mypkg

import "fmt"

func SayHello() {
	fmt.Println("Hello")
}
```

```go
// go.mod
module testbom

go 1.14
```

when I use `go build main.go` to compile it, it failed.  I found it's because the go source code cannot read the UTF8-BOM.
so I edit the souece code of  `go/src/cmd/go/internal/imports/scan.go`

```go
func scanFiles(files []string, tags map[string]bool, explicitFiles bool) ([]string, []string, error) {
	imports := make(map[string]bool)
	testImports := make(map[string]bool)
	numFiles := 0
Files:
	for _, name := range files {
		r, err := os.Open(name)
		if err != nil {
			return nil, nil, err
		}
               
               // I add these code to check if the source code is with BOM
		var fheader = make([]byte, 3)
		_, err = r.Read(fheader)
		if err != nil {
			fmt.Println("error: ", err)
		}
		if fheader[0] == 0xef && fheader[1] == 0xbb && fheader[2] == 0xbf {
			r.Seek(3, 0)
		} else {
			r.Seek(0, 0)
		}
                ///////////////////////////////////////////

		var list []string
                // if a file is with BOM, the return list is empty
		data, err := ReadImports(r, false, &list)
		r.Close()
		if err != nil {
			return nil, nil, fmt.Errorf("reading %s: %v", name, err)
		}
// ... ...
}
```

and then, I recompile the golang. when I compile the code above, it success. <br>
I hope you can confirm soon whether there is this problem, because many people use files with BOM. <br>
thanks for reading.

### What did you expect to see?

compile success

### What did you see instead?

main.go:5:2: cannot find package

### PR DESCRIPTION
**Pull request by unbyte**
Fix the problem that UTF8 BOM can cause the parsing of import path and directives to fail.

Fixes #46198 
Fixes #46290
Fixes #35726

### CODE REVIEW

**Comment by LiuYinCarl** [comment]
If the source code's coding is UTF16-BOM or any other UTF-BOM coding except UTF8-BOM, is it means your pull request cannot deal with this situation?

**Comment by unbyte** [comment]
> If the source code's coding is UTF16-BOM or any other UTF-BOM coding except UTF8-BOM, is it means your pull request cannot deal with this situation?

As mentioned in https://golang.org/ref/spec#Source_code_representation, **Source code is Unicode text encoded in UTF-8.**

So don't worry about UTF16-BOM and else 😀

**Comment by LiuYinCarl** [comment]
thanks for your answer. Another question about BOM, in [scanner.go](https://github.com/golang/go/blob/master/src/go/scanner/scanner.go)

the bom define as 
```go

const (
	bom = 0xFEFF // byte order mark, only permitted as very first character	
        eof = -1     // end of file
)
```

and use as
```go
func (s *Scanner) Init(file *token.File, src []byte, err ErrorHandler, mode Mode) {
        // ... ...
	s.next()
	if s.ch == bom {
		s.next() // ignore BOM at file beginning
	}
}
```
I know UTF8-BOM file's BOM is `0xefbbbf`, and UTF16-BOM is `0xFEFF`, according to your link above,  is `scanner.go` wrong?

**Comment by unbyte** [comment]
> I know UTF8-BOM file's BOM is 0xefbbbf, and UTF16-BOM is 0xFEFF, according to your link above, is scanner.go wrong?

In the earliest related commit, `\ufeff` is used rather than `0xfeff`. I don't know if this is a intentional modification.

**Comment by Appla** [comment]
> thanks for your answer. Another question about BOM, in [scanner.go](https://github.com/golang/go/blob/master/src/go/scanner/scanner.go)
> 
> the bom define as
> 
> ```go
> const (
> 	bom = 0xFEFF // byte order mark, only permitted as very first character	
>         eof = -1     // end of file
> )
> ```
> 
> and use as
> 
> ```go
> func (s *Scanner) Init(file *token.File, src []byte, err ErrorHandler, mode Mode) {
>         // ... ...
> 	s.next()
> 	if s.ch == bom {
> 		s.next() // ignore BOM at file beginning
> 	}
> }
> ```
> 
> I know UTF8-BOM file's BOM is `0xefbbbf`, and UTF16-BOM is `0xFEFF`, according to your link above, is `scanner.go` wrong?

it's rune type in scanner.go
